# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hal/adapters/common/v1/common.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'hal/adapters/common/v1/common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#hal/adapters/common/v1/common.proto\x12\x16hal.adapters.common.v1\"\x14\n\x12HealthCheckRequest\"&\n\x13HealthCheckResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"G\n\x1aResourceHealthCheckRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x15\n\rresource_type\x18\x02 \x01(\t\".\n\x1bResourceHealthCheckResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"?\n\x12\x41utoRecoverRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x15\n\rresource_type\x18\x02 \x01(\t\"&\n\x13\x41utoRecoverResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"M\n\x0bTuneRequest\x12\x12\n\nproduct_id\x18\x01 \x01(\t\x12\x13\n\x0b\x63onfig_json\x18\x02 \x01(\t\x12\x15\n\rresource_type\x18\x03 \x01(\t\"\x1f\n\x0cTuneResponse\x12\x0f\n\x07message\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hal.adapters.common.v1.common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHCHECKREQUEST']._serialized_start=63
  _globals['_HEALTHCHECKREQUEST']._serialized_end=83
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=85
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=123
  _globals['_RESOURCEHEALTHCHECKREQUEST']._serialized_start=125
  _globals['_RESOURCEHEALTHCHECKREQUEST']._serialized_end=196
  _globals['_RESOURCEHEALTHCHECKRESPONSE']._serialized_start=198
  _globals['_RESOURCEHEALTHCHECKRESPONSE']._serialized_end=244
  _globals['_AUTORECOVERREQUEST']._serialized_start=246
  _globals['_AUTORECOVERREQUEST']._serialized_end=309
  _globals['_AUTORECOVERRESPONSE']._serialized_start=311
  _globals['_AUTORECOVERRESPONSE']._serialized_end=349
  _globals['_TUNEREQUEST']._serialized_start=351
  _globals['_TUNEREQUEST']._serialized_end=428
  _globals['_TUNERESPONSE']._serialized_start=430
  _globals['_TUNERESPONSE']._serialized_end=461
# @@protoc_insertion_point(module_scope)
