# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from hal.adapters.common.v1 import common_pb2 as hal_dot_adapters_dot_common_dot_v1_dot_common__pb2
from hal.adapters.source.v1 import source_pb2 as hal_dot_adapters_dot_source_dot_v1_dot_source__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hal/adapters/source/v1/source_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AdapterSourceServiceStub:
    """--- Liveness & discovery ---
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/hal.adapters.source.v1.AdapterSourceService/HealthCheck',
                request_serializer=hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.ResourceHealthCheck = channel.unary_unary(
                '/hal.adapters.source.v1.AdapterSourceService/ResourceHealthCheck',
                request_serializer=hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.ResourceHealthCheckRequest.SerializeToString,
                response_deserializer=hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.ResourceHealthCheckResponse.FromString,
                _registered_method=True)
        self.GetProductInfo = channel.unary_unary(
                '/hal.adapters.source.v1.AdapterSourceService/GetProductInfo',
                request_serializer=hal_dot_adapters_dot_source_dot_v1_dot_source__pb2.GetProductInfoRequest.SerializeToString,
                response_deserializer=hal_dot_adapters_dot_source_dot_v1_dot_source__pb2.GetProductInfoResponse.FromString,
                _registered_method=True)
        self.Initialize = channel.unary_unary(
                '/hal.adapters.source.v1.AdapterSourceService/Initialize',
                request_serializer=hal_dot_adapters_dot_source_dot_v1_dot_source__pb2.InitializeRequest.SerializeToString,
                response_deserializer=hal_dot_adapters_dot_source_dot_v1_dot_source__pb2.InitializeResponse.FromString,
                _registered_method=True)
        self.Deinitialize = channel.unary_unary(
                '/hal.adapters.source.v1.AdapterSourceService/Deinitialize',
                request_serializer=hal_dot_adapters_dot_source_dot_v1_dot_source__pb2.DeinitializeRequest.SerializeToString,
                response_deserializer=hal_dot_adapters_dot_source_dot_v1_dot_source__pb2.DeinitializeResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/hal.adapters.source.v1.AdapterSourceService/GetStatus',
                request_serializer=hal_dot_adapters_dot_source_dot_v1_dot_source__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=hal_dot_adapters_dot_source_dot_v1_dot_source__pb2.GetStatusResponse.FromString,
                _registered_method=True)
        self.SetConfig = channel.unary_unary(
                '/hal.adapters.source.v1.AdapterSourceService/SetConfig',
                request_serializer=hal_dot_adapters_dot_source_dot_v1_dot_source__pb2.SetConfigRequest.SerializeToString,
                response_deserializer=hal_dot_adapters_dot_source_dot_v1_dot_source__pb2.SetConfigResponse.FromString,
                _registered_method=True)
        self.AutoRecover = channel.unary_unary(
                '/hal.adapters.source.v1.AdapterSourceService/AutoRecover',
                request_serializer=hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.AutoRecoverRequest.SerializeToString,
                response_deserializer=hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.AutoRecoverResponse.FromString,
                _registered_method=True)
        self.Tune = channel.unary_unary(
                '/hal.adapters.source.v1.AdapterSourceService/Tune',
                request_serializer=hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.TuneRequest.SerializeToString,
                response_deserializer=hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.TuneResponse.FromString,
                _registered_method=True)
        self.StartEmission = channel.unary_unary(
                '/hal.adapters.source.v1.AdapterSourceService/StartEmission',
                request_serializer=hal_dot_adapters_dot_source_dot_v1_dot_source__pb2.StartEmissionRequest.SerializeToString,
                response_deserializer=hal_dot_adapters_dot_source_dot_v1_dot_source__pb2.StartEmissionResponse.FromString,
                _registered_method=True)
        self.StopEmission = channel.unary_unary(
                '/hal.adapters.source.v1.AdapterSourceService/StopEmission',
                request_serializer=hal_dot_adapters_dot_source_dot_v1_dot_source__pb2.StopEmissionRequest.SerializeToString,
                response_deserializer=hal_dot_adapters_dot_source_dot_v1_dot_source__pb2.StopEmissionResponse.FromString,
                _registered_method=True)
        self.TriggerEvent = channel.unary_unary(
                '/hal.adapters.source.v1.AdapterSourceService/TriggerEvent',
                request_serializer=hal_dot_adapters_dot_source_dot_v1_dot_source__pb2.TriggerEventRequest.SerializeToString,
                response_deserializer=hal_dot_adapters_dot_source_dot_v1_dot_source__pb2.TriggerEventResponse.FromString,
                _registered_method=True)


class AdapterSourceServiceServicer:
    """--- Liveness & discovery ---
    """

    def HealthCheck(self, request, context):
        """Liveness of the adapter process itself. See common.proto.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResourceHealthCheck(self, request, context):
        """Health of the physical source hardware behind the adapter. See
        common.proto; the UP / DOWN / DEGRADED-style result may be informed by
        the device's current SourceState.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProductInfo(self, request, context):
        """Static identity of the hardware behind the adapter: serial number,
        vendor, firmware/software version.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Initialize(self, request, context):
        """--- Lifecycle ---

        Brings the source from a freshly power-cycled state to
        SOURCE_STATE_READY: applies the operating configuration (pump power,
        temperature/TEC setpoint, laser locking, etc.) and runs whatever
        bring-up sequence the hardware needs. Returns as soon as the sequence
        is accepted -- bring-up can take minutes and cannot sit inside a call
        the caller has a deadline on -- so callers poll GetStatus until the
        state reaches READY or FAULT.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Deinitialize(self, request, context):
        """The opposite of Initialize: orderly shutdown once all jobs are done --
        turns off the pump laser and de-energizes whatever else Initialize
        brought up -- back toward SOURCE_STATE_IDLE.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """--- Status & configuration ---

        Current lifecycle state and health of the source, plus which run (if
        any) it is bound to. Poll this after Initialize/Deinitialize, and
        during emission.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetConfig(self, request, context):
        """Updates the source's operating configuration without a full
        Initialize/Deinitialize cycle.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AutoRecover(self, request, context):
        """--- Recovery ---

        Attempts the adapter's built-in automated recovery sequence to bring
        the source back from SOURCE_STATE_DEGRADED (or FAULT) toward READY --
        e.g. re-running the resonance lock, restarting the pump laser, or
        whatever vendor-specific remediation applies. See common.proto. Returns
        as soon as the sequence is accepted -- recovery can take as long as
        Initialize -- so callers poll GetStatus for the outcome.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Tune(self, request, context):
        """Applies a single targeted adjustment as an alternative to a full
        AutoRecover sequence -- e.g. nudge one setpoint rather than re-running
        the whole remediation. See common.proto. Vendor-specific; adapters with
        no such fine-grained control may return UNIMPLEMENTED.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartEmission(self, request, context):
        """--- Emission (job) control ---

        Starts generating entanglement pairs for the given run. Called when
        the controller begins a job -- e.g. an entanglement-distribution
        intent between two endpoints. Requires SOURCE_STATE_READY; moves the
        source into SOURCE_STATE_EMITTING for the duration of the run.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopEmission(self, request, context):
        """Stops generating entanglement pairs and returns the source to
        SOURCE_STATE_READY, available for the next job.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerEvent(self, request, context):
        """--- Special actions (optional) ---

        Triggers a special, adapter-defined action for a running job -- not
        limited to fault/emulation scenarios (e.g. an induced fault or an
        environmental perturbation for testing); anything else the device
        might need done mid-run that doesn't fit the RPCs above. Optional: an
        adapter with no such capability may return UNIMPLEMENTED.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdapterSourceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.HealthCheckRequest.FromString,
                    response_serializer=hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.HealthCheckResponse.SerializeToString,
            ),
            'ResourceHealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.ResourceHealthCheck,
                    request_deserializer=hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.ResourceHealthCheckRequest.FromString,
                    response_serializer=hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.ResourceHealthCheckResponse.SerializeToString,
            ),
            'GetProductInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProductInfo,
                    request_deserializer=hal_dot_adapters_dot_source_dot_v1_dot_source__pb2.GetProductInfoRequest.FromString,
                    response_serializer=hal_dot_adapters_dot_source_dot_v1_dot_source__pb2.GetProductInfoResponse.SerializeToString,
            ),
            'Initialize': grpc.unary_unary_rpc_method_handler(
                    servicer.Initialize,
                    request_deserializer=hal_dot_adapters_dot_source_dot_v1_dot_source__pb2.InitializeRequest.FromString,
                    response_serializer=hal_dot_adapters_dot_source_dot_v1_dot_source__pb2.InitializeResponse.SerializeToString,
            ),
            'Deinitialize': grpc.unary_unary_rpc_method_handler(
                    servicer.Deinitialize,
                    request_deserializer=hal_dot_adapters_dot_source_dot_v1_dot_source__pb2.DeinitializeRequest.FromString,
                    response_serializer=hal_dot_adapters_dot_source_dot_v1_dot_source__pb2.DeinitializeResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=hal_dot_adapters_dot_source_dot_v1_dot_source__pb2.GetStatusRequest.FromString,
                    response_serializer=hal_dot_adapters_dot_source_dot_v1_dot_source__pb2.GetStatusResponse.SerializeToString,
            ),
            'SetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SetConfig,
                    request_deserializer=hal_dot_adapters_dot_source_dot_v1_dot_source__pb2.SetConfigRequest.FromString,
                    response_serializer=hal_dot_adapters_dot_source_dot_v1_dot_source__pb2.SetConfigResponse.SerializeToString,
            ),
            'AutoRecover': grpc.unary_unary_rpc_method_handler(
                    servicer.AutoRecover,
                    request_deserializer=hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.AutoRecoverRequest.FromString,
                    response_serializer=hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.AutoRecoverResponse.SerializeToString,
            ),
            'Tune': grpc.unary_unary_rpc_method_handler(
                    servicer.Tune,
                    request_deserializer=hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.TuneRequest.FromString,
                    response_serializer=hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.TuneResponse.SerializeToString,
            ),
            'StartEmission': grpc.unary_unary_rpc_method_handler(
                    servicer.StartEmission,
                    request_deserializer=hal_dot_adapters_dot_source_dot_v1_dot_source__pb2.StartEmissionRequest.FromString,
                    response_serializer=hal_dot_adapters_dot_source_dot_v1_dot_source__pb2.StartEmissionResponse.SerializeToString,
            ),
            'StopEmission': grpc.unary_unary_rpc_method_handler(
                    servicer.StopEmission,
                    request_deserializer=hal_dot_adapters_dot_source_dot_v1_dot_source__pb2.StopEmissionRequest.FromString,
                    response_serializer=hal_dot_adapters_dot_source_dot_v1_dot_source__pb2.StopEmissionResponse.SerializeToString,
            ),
            'TriggerEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerEvent,
                    request_deserializer=hal_dot_adapters_dot_source_dot_v1_dot_source__pb2.TriggerEventRequest.FromString,
                    response_serializer=hal_dot_adapters_dot_source_dot_v1_dot_source__pb2.TriggerEventResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hal.adapters.source.v1.AdapterSourceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hal.adapters.source.v1.AdapterSourceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AdapterSourceService:
    """--- Liveness & discovery ---
    """

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hal.adapters.source.v1.AdapterSourceService/HealthCheck',
            hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.HealthCheckRequest.SerializeToString,
            hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResourceHealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hal.adapters.source.v1.AdapterSourceService/ResourceHealthCheck',
            hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.ResourceHealthCheckRequest.SerializeToString,
            hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.ResourceHealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProductInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hal.adapters.source.v1.AdapterSourceService/GetProductInfo',
            hal_dot_adapters_dot_source_dot_v1_dot_source__pb2.GetProductInfoRequest.SerializeToString,
            hal_dot_adapters_dot_source_dot_v1_dot_source__pb2.GetProductInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Initialize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hal.adapters.source.v1.AdapterSourceService/Initialize',
            hal_dot_adapters_dot_source_dot_v1_dot_source__pb2.InitializeRequest.SerializeToString,
            hal_dot_adapters_dot_source_dot_v1_dot_source__pb2.InitializeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Deinitialize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hal.adapters.source.v1.AdapterSourceService/Deinitialize',
            hal_dot_adapters_dot_source_dot_v1_dot_source__pb2.DeinitializeRequest.SerializeToString,
            hal_dot_adapters_dot_source_dot_v1_dot_source__pb2.DeinitializeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hal.adapters.source.v1.AdapterSourceService/GetStatus',
            hal_dot_adapters_dot_source_dot_v1_dot_source__pb2.GetStatusRequest.SerializeToString,
            hal_dot_adapters_dot_source_dot_v1_dot_source__pb2.GetStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hal.adapters.source.v1.AdapterSourceService/SetConfig',
            hal_dot_adapters_dot_source_dot_v1_dot_source__pb2.SetConfigRequest.SerializeToString,
            hal_dot_adapters_dot_source_dot_v1_dot_source__pb2.SetConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AutoRecover(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hal.adapters.source.v1.AdapterSourceService/AutoRecover',
            hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.AutoRecoverRequest.SerializeToString,
            hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.AutoRecoverResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Tune(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hal.adapters.source.v1.AdapterSourceService/Tune',
            hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.TuneRequest.SerializeToString,
            hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.TuneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartEmission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hal.adapters.source.v1.AdapterSourceService/StartEmission',
            hal_dot_adapters_dot_source_dot_v1_dot_source__pb2.StartEmissionRequest.SerializeToString,
            hal_dot_adapters_dot_source_dot_v1_dot_source__pb2.StartEmissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopEmission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hal.adapters.source.v1.AdapterSourceService/StopEmission',
            hal_dot_adapters_dot_source_dot_v1_dot_source__pb2.StopEmissionRequest.SerializeToString,
            hal_dot_adapters_dot_source_dot_v1_dot_source__pb2.StopEmissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hal.adapters.source.v1.AdapterSourceService/TriggerEvent',
            hal_dot_adapters_dot_source_dot_v1_dot_source__pb2.TriggerEventRequest.SerializeToString,
            hal_dot_adapters_dot_source_dot_v1_dot_source__pb2.TriggerEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
