// Copyright 2026 Cisco Systems, Inc. and its affiliates
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: hal/adapters/common/v1/common.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Liveness of the adapter process itself (UP/DOWN), independent of the
// hardware it manages. Never reaches the device. Takes no arguments.
type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_hal_adapters_common_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_common_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_hal_adapters_common_v1_common_proto_rawDescGZIP(), []int{0}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_hal_adapters_common_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_common_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_hal_adapters_common_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Health of the physical hardware behind the adapter, as reported by the
// vendor's own driver/API for that device -- not just process liveness.
// Implementations query whatever the vendor exposes and translate it into
// an UP / DOWN / DEGRADED-style result, which may be informed by the
// device's own lifecycle state enum.
type ResourceHealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ResourceType  string                 `protobuf:"bytes,2,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceHealthCheckRequest) Reset() {
	*x = ResourceHealthCheckRequest{}
	mi := &file_hal_adapters_common_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceHealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceHealthCheckRequest) ProtoMessage() {}

func (x *ResourceHealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_common_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceHealthCheckRequest.ProtoReflect.Descriptor instead.
func (*ResourceHealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_hal_adapters_common_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceHealthCheckRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ResourceHealthCheckRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

type ResourceHealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceHealthCheckResponse) Reset() {
	*x = ResourceHealthCheckResponse{}
	mi := &file_hal_adapters_common_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceHealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceHealthCheckResponse) ProtoMessage() {}

func (x *ResourceHealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_common_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceHealthCheckResponse.ProtoReflect.Descriptor instead.
func (*ResourceHealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_hal_adapters_common_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *ResourceHealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Attempts the adapter's built-in automated recovery sequence to bring the
// device back from its DEGRADED (or FAULT) state toward READY -- whatever
// vendor-specific remediation applies. Safe to call at any time; a no-op if
// the device isn't degraded.
type AutoRecoverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ResourceType  string                 `protobuf:"bytes,2,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutoRecoverRequest) Reset() {
	*x = AutoRecoverRequest{}
	mi := &file_hal_adapters_common_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoRecoverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoRecoverRequest) ProtoMessage() {}

func (x *AutoRecoverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_common_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoRecoverRequest.ProtoReflect.Descriptor instead.
func (*AutoRecoverRequest) Descriptor() ([]byte, []int) {
	return file_hal_adapters_common_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *AutoRecoverRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *AutoRecoverRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

type AutoRecoverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutoRecoverResponse) Reset() {
	*x = AutoRecoverResponse{}
	mi := &file_hal_adapters_common_v1_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoRecoverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoRecoverResponse) ProtoMessage() {}

func (x *AutoRecoverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_common_v1_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoRecoverResponse.ProtoReflect.Descriptor instead.
func (*AutoRecoverResponse) Descriptor() ([]byte, []int) {
	return file_hal_adapters_common_v1_common_proto_rawDescGZIP(), []int{5}
}

func (x *AutoRecoverResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Applies a single targeted adjustment as an alternative to a full
// AutoRecover sequence. Vendor-specific tuning parameters (which setpoint
// to adjust, target value, etc.), encoded as a JSON object; each product's
// adapter implementation defines and documents its own schema for
// config_json and is responsible for parsing it.
type TuneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ConfigJson    string                 `protobuf:"bytes,2,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	ResourceType  string                 `protobuf:"bytes,3,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TuneRequest) Reset() {
	*x = TuneRequest{}
	mi := &file_hal_adapters_common_v1_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TuneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TuneRequest) ProtoMessage() {}

func (x *TuneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_common_v1_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TuneRequest.ProtoReflect.Descriptor instead.
func (*TuneRequest) Descriptor() ([]byte, []int) {
	return file_hal_adapters_common_v1_common_proto_rawDescGZIP(), []int{6}
}

func (x *TuneRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *TuneRequest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

func (x *TuneRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

type TuneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TuneResponse) Reset() {
	*x = TuneResponse{}
	mi := &file_hal_adapters_common_v1_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TuneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TuneResponse) ProtoMessage() {}

func (x *TuneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_common_v1_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TuneResponse.ProtoReflect.Descriptor instead.
func (*TuneResponse) Descriptor() ([]byte, []int) {
	return file_hal_adapters_common_v1_common_proto_rawDescGZIP(), []int{7}
}

func (x *TuneResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_hal_adapters_common_v1_common_proto protoreflect.FileDescriptor

const file_hal_adapters_common_v1_common_proto_rawDesc = "" +
	"\n" +
	"#hal/adapters/common/v1/common.proto\x12\x16hal.adapters.common.v1\"\x14\n" +
	"\x12HealthCheckRequest\"/\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"`\n" +
	"\x1aResourceHealthCheckRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12#\n" +
	"\rresource_type\x18\x02 \x01(\tR\fresourceType\"7\n" +
	"\x1bResourceHealthCheckResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"X\n" +
	"\x12AutoRecoverRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12#\n" +
	"\rresource_type\x18\x02 \x01(\tR\fresourceType\"/\n" +
	"\x13AutoRecoverResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"r\n" +
	"\vTuneRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1f\n" +
	"\vconfig_json\x18\x02 \x01(\tR\n" +
	"configJson\x12#\n" +
	"\rresource_type\x18\x03 \x01(\tR\fresourceType\"(\n" +
	"\fTuneResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessageB\xf1\x01\n" +
	"\x1acom.hal.adapters.common.v1B\vCommonProtoP\x01ZKgithub.com/outshift-open/quantum-hal/sdk/go/hal/adapters/common/v1;commonv1\xa2\x02\x03HAC\xaa\x02\x16Hal.Adapters.Common.V1\xca\x02\x16Hal\\Adapters\\Common\\V1\xe2\x02\"Hal\\Adapters\\Common\\V1\\GPBMetadata\xea\x02\x19Hal::Adapters::Common::V1b\x06proto3"

var (
	file_hal_adapters_common_v1_common_proto_rawDescOnce sync.Once
	file_hal_adapters_common_v1_common_proto_rawDescData []byte
)

func file_hal_adapters_common_v1_common_proto_rawDescGZIP() []byte {
	file_hal_adapters_common_v1_common_proto_rawDescOnce.Do(func() {
		file_hal_adapters_common_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hal_adapters_common_v1_common_proto_rawDesc), len(file_hal_adapters_common_v1_common_proto_rawDesc)))
	})
	return file_hal_adapters_common_v1_common_proto_rawDescData
}

var file_hal_adapters_common_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_hal_adapters_common_v1_common_proto_goTypes = []any{
	(*HealthCheckRequest)(nil),          // 0: hal.adapters.common.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),         // 1: hal.adapters.common.v1.HealthCheckResponse
	(*ResourceHealthCheckRequest)(nil),  // 2: hal.adapters.common.v1.ResourceHealthCheckRequest
	(*ResourceHealthCheckResponse)(nil), // 3: hal.adapters.common.v1.ResourceHealthCheckResponse
	(*AutoRecoverRequest)(nil),          // 4: hal.adapters.common.v1.AutoRecoverRequest
	(*AutoRecoverResponse)(nil),         // 5: hal.adapters.common.v1.AutoRecoverResponse
	(*TuneRequest)(nil),                 // 6: hal.adapters.common.v1.TuneRequest
	(*TuneResponse)(nil),                // 7: hal.adapters.common.v1.TuneResponse
}
var file_hal_adapters_common_v1_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hal_adapters_common_v1_common_proto_init() }
func file_hal_adapters_common_v1_common_proto_init() {
	if File_hal_adapters_common_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hal_adapters_common_v1_common_proto_rawDesc), len(file_hal_adapters_common_v1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hal_adapters_common_v1_common_proto_goTypes,
		DependencyIndexes: file_hal_adapters_common_v1_common_proto_depIdxs,
		MessageInfos:      file_hal_adapters_common_v1_common_proto_msgTypes,
	}.Build()
	File_hal_adapters_common_v1_common_proto = out.File
	file_hal_adapters_common_v1_common_proto_goTypes = nil
	file_hal_adapters_common_v1_common_proto_depIdxs = nil
}
