# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from hal.adapters.common.v1 import common_pb2 as hal_dot_adapters_dot_common_dot_v1_dot_common__pb2
from hal.adapters.switch.v1 import switch_pb2 as hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hal/adapters/switch/v1/switch_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AdapterSwitchServiceStub:
    """--- Liveness & discovery ---
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/hal.adapters.switch.v1.AdapterSwitchService/HealthCheck',
                request_serializer=hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.ResourceHealthCheck = channel.unary_unary(
                '/hal.adapters.switch.v1.AdapterSwitchService/ResourceHealthCheck',
                request_serializer=hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.ResourceHealthCheckRequest.SerializeToString,
                response_deserializer=hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.ResourceHealthCheckResponse.FromString,
                _registered_method=True)
        self.GetProductInfo = channel.unary_unary(
                '/hal.adapters.switch.v1.AdapterSwitchService/GetProductInfo',
                request_serializer=hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.GetProductInfoRequest.SerializeToString,
                response_deserializer=hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.GetProductInfoResponse.FromString,
                _registered_method=True)
        self.Initialize = channel.unary_unary(
                '/hal.adapters.switch.v1.AdapterSwitchService/Initialize',
                request_serializer=hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.InitializeRequest.SerializeToString,
                response_deserializer=hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.InitializeResponse.FromString,
                _registered_method=True)
        self.Deinitialize = channel.unary_unary(
                '/hal.adapters.switch.v1.AdapterSwitchService/Deinitialize',
                request_serializer=hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.DeinitializeRequest.SerializeToString,
                response_deserializer=hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.DeinitializeResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/hal.adapters.switch.v1.AdapterSwitchService/GetStatus',
                request_serializer=hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.GetStatusResponse.FromString,
                _registered_method=True)
        self.SetConfig = channel.unary_unary(
                '/hal.adapters.switch.v1.AdapterSwitchService/SetConfig',
                request_serializer=hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.SetConfigRequest.SerializeToString,
                response_deserializer=hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.SetConfigResponse.FromString,
                _registered_method=True)
        self.AutoRecover = channel.unary_unary(
                '/hal.adapters.switch.v1.AdapterSwitchService/AutoRecover',
                request_serializer=hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.AutoRecoverRequest.SerializeToString,
                response_deserializer=hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.AutoRecoverResponse.FromString,
                _registered_method=True)
        self.Tune = channel.unary_unary(
                '/hal.adapters.switch.v1.AdapterSwitchService/Tune',
                request_serializer=hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.TuneRequest.SerializeToString,
                response_deserializer=hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.TuneResponse.FromString,
                _registered_method=True)
        self.CommitConnection = channel.unary_unary(
                '/hal.adapters.switch.v1.AdapterSwitchService/CommitConnection',
                request_serializer=hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.CommitConnectionRequest.SerializeToString,
                response_deserializer=hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.CommitConnectionResponse.FromString,
                _registered_method=True)
        self.ClearConnections = channel.unary_unary(
                '/hal.adapters.switch.v1.AdapterSwitchService/ClearConnections',
                request_serializer=hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.ClearConnectionsRequest.SerializeToString,
                response_deserializer=hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.ClearConnectionsResponse.FromString,
                _registered_method=True)
        self.ExecuteCommand = channel.unary_unary(
                '/hal.adapters.switch.v1.AdapterSwitchService/ExecuteCommand',
                request_serializer=hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.ExecuteCommandRequest.SerializeToString,
                response_deserializer=hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.ExecuteCommandResponse.FromString,
                _registered_method=True)
        self.TriggerEvent = channel.unary_unary(
                '/hal.adapters.switch.v1.AdapterSwitchService/TriggerEvent',
                request_serializer=hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.TriggerEventRequest.SerializeToString,
                response_deserializer=hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.TriggerEventResponse.FromString,
                _registered_method=True)


class AdapterSwitchServiceServicer:
    """--- Liveness & discovery ---
    """

    def HealthCheck(self, request, context):
        """Liveness of the adapter process itself. See common.proto.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResourceHealthCheck(self, request, context):
        """Health of the physical switch hardware behind the adapter. See
        common.proto; the UP / DOWN / DEGRADED-style result may be informed by
        the device's current SwitchState.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProductInfo(self, request, context):
        """Static identity of the hardware behind the adapter: serial number,
        vendor, firmware/software version, and the switch matrix size(s) it
        exposes.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Initialize(self, request, context):
        """--- Lifecycle ---

        Brings the switch from a freshly power-cycled state to ready-to-route:
        homes/calibrates the switch fabric (e.g. MEMS mirror homing, fiber
        alignment) and runs whatever self-test the hardware needs. Unlike
        source's Initialize, switch homing is a short operation -- this call is
        expected to block until it completes rather than requiring a status
        poll.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Deinitialize(self, request, context):
        """The opposite of Initialize: orderly shutdown once the switch is no
        longer needed -- parks the switch fabric and releases whatever
        Initialize acquired.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """--- Status & configuration ---

        Current lifecycle state of the switch, plus its uptime. Poll this after
        Initialize/Deinitialize.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetConfig(self, request, context):
        """Updates the switch's operating configuration without a full
        Initialize/Deinitialize cycle.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AutoRecover(self, request, context):
        """--- Recovery ---

        Attempts the adapter's built-in automated recovery sequence to bring
        the switch back from SWITCH_STATE_DEGRADED (or FAULT) toward READY --
        e.g. re-homing the fabric or whatever vendor-specific remediation
        applies. See common.proto. Like Initialize, this is expected to block
        until it completes rather than requiring a status poll.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Tune(self, request, context):
        """Applies a single targeted adjustment as an alternative to a full
        AutoRecover sequence -- e.g. re-home one path rather than the whole
        fabric. See common.proto. Vendor-specific; adapters with no such
        fine-grained control may return UNIMPLEMENTED.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitConnection(self, request, context):
        """--- Connection control ---

        Establishes (or replaces) a signal path from input_port to output_port.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearConnections(self, request, context):
        """Tears down the connections on the given ports, freeing them for reuse.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteCommand(self, request, context):
        """--- Raw command (optional) ---

        Vendor-specific passthrough for commands not covered by the RPCs above
        (e.g. a diagnostic or provisioning command with no structured
        equivalent here). Implementing this RPC is optional: an adapter with no
        need for raw command passthrough may return UNIMPLEMENTED.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerEvent(self, request, context):
        """--- Special actions (optional) ---

        Triggers a special, adapter-defined action -- not limited to
        fault/emulation scenarios (e.g. an induced fault or an environmental
        perturbation for testing); anything else the device might need done
        mid-job that doesn't fit the RPCs above. Optional: an adapter with no
        such capability may return UNIMPLEMENTED.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdapterSwitchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.HealthCheckRequest.FromString,
                    response_serializer=hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.HealthCheckResponse.SerializeToString,
            ),
            'ResourceHealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.ResourceHealthCheck,
                    request_deserializer=hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.ResourceHealthCheckRequest.FromString,
                    response_serializer=hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.ResourceHealthCheckResponse.SerializeToString,
            ),
            'GetProductInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProductInfo,
                    request_deserializer=hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.GetProductInfoRequest.FromString,
                    response_serializer=hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.GetProductInfoResponse.SerializeToString,
            ),
            'Initialize': grpc.unary_unary_rpc_method_handler(
                    servicer.Initialize,
                    request_deserializer=hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.InitializeRequest.FromString,
                    response_serializer=hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.InitializeResponse.SerializeToString,
            ),
            'Deinitialize': grpc.unary_unary_rpc_method_handler(
                    servicer.Deinitialize,
                    request_deserializer=hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.DeinitializeRequest.FromString,
                    response_serializer=hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.DeinitializeResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.GetStatusRequest.FromString,
                    response_serializer=hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.GetStatusResponse.SerializeToString,
            ),
            'SetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SetConfig,
                    request_deserializer=hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.SetConfigRequest.FromString,
                    response_serializer=hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.SetConfigResponse.SerializeToString,
            ),
            'AutoRecover': grpc.unary_unary_rpc_method_handler(
                    servicer.AutoRecover,
                    request_deserializer=hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.AutoRecoverRequest.FromString,
                    response_serializer=hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.AutoRecoverResponse.SerializeToString,
            ),
            'Tune': grpc.unary_unary_rpc_method_handler(
                    servicer.Tune,
                    request_deserializer=hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.TuneRequest.FromString,
                    response_serializer=hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.TuneResponse.SerializeToString,
            ),
            'CommitConnection': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitConnection,
                    request_deserializer=hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.CommitConnectionRequest.FromString,
                    response_serializer=hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.CommitConnectionResponse.SerializeToString,
            ),
            'ClearConnections': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearConnections,
                    request_deserializer=hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.ClearConnectionsRequest.FromString,
                    response_serializer=hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.ClearConnectionsResponse.SerializeToString,
            ),
            'ExecuteCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteCommand,
                    request_deserializer=hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.ExecuteCommandRequest.FromString,
                    response_serializer=hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.ExecuteCommandResponse.SerializeToString,
            ),
            'TriggerEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerEvent,
                    request_deserializer=hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.TriggerEventRequest.FromString,
                    response_serializer=hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.TriggerEventResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hal.adapters.switch.v1.AdapterSwitchService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hal.adapters.switch.v1.AdapterSwitchService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AdapterSwitchService:
    """--- Liveness & discovery ---
    """

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hal.adapters.switch.v1.AdapterSwitchService/HealthCheck',
            hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.HealthCheckRequest.SerializeToString,
            hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResourceHealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hal.adapters.switch.v1.AdapterSwitchService/ResourceHealthCheck',
            hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.ResourceHealthCheckRequest.SerializeToString,
            hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.ResourceHealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProductInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hal.adapters.switch.v1.AdapterSwitchService/GetProductInfo',
            hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.GetProductInfoRequest.SerializeToString,
            hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.GetProductInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Initialize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hal.adapters.switch.v1.AdapterSwitchService/Initialize',
            hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.InitializeRequest.SerializeToString,
            hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.InitializeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Deinitialize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hal.adapters.switch.v1.AdapterSwitchService/Deinitialize',
            hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.DeinitializeRequest.SerializeToString,
            hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.DeinitializeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hal.adapters.switch.v1.AdapterSwitchService/GetStatus',
            hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.GetStatusRequest.SerializeToString,
            hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.GetStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hal.adapters.switch.v1.AdapterSwitchService/SetConfig',
            hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.SetConfigRequest.SerializeToString,
            hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.SetConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AutoRecover(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hal.adapters.switch.v1.AdapterSwitchService/AutoRecover',
            hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.AutoRecoverRequest.SerializeToString,
            hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.AutoRecoverResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Tune(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hal.adapters.switch.v1.AdapterSwitchService/Tune',
            hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.TuneRequest.SerializeToString,
            hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.TuneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitConnection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hal.adapters.switch.v1.AdapterSwitchService/CommitConnection',
            hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.CommitConnectionRequest.SerializeToString,
            hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.CommitConnectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearConnections(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hal.adapters.switch.v1.AdapterSwitchService/ClearConnections',
            hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.ClearConnectionsRequest.SerializeToString,
            hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.ClearConnectionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hal.adapters.switch.v1.AdapterSwitchService/ExecuteCommand',
            hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.ExecuteCommandRequest.SerializeToString,
            hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.ExecuteCommandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hal.adapters.switch.v1.AdapterSwitchService/TriggerEvent',
            hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.TriggerEventRequest.SerializeToString,
            hal_dot_adapters_dot_switch_dot_v1_dot_switch__pb2.TriggerEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
