// Copyright 2026 Cisco Systems, Inc. and its affiliates
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: hal/adapters/source/v1/source.proto

package sourcev1

import (
	v1 "github.com/outshift-open/quantum-hal/sdk/go/hal/adapters/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Lifecycle of the source hardware.
//
// Values 1-3 predate the lifecycle work and keep their original numbers so
// already-generated stubs stay wire-compatible.  SOURCE_STATE_IDLE is the
// "powered, no loops running" state -- the OFF of the state machine.
type SourceState int32

const (
	SourceState_SOURCE_STATE_UNSPECIFIED SourceState = 0
	SourceState_SOURCE_STATE_IDLE        SourceState = 1
	// Actively generating entanglement pairs for the run bound via
	// StartEmission -- the "busy" state; not available for a new job until
	// StopEmission returns it to READY.
	SourceState_SOURCE_STATE_EMITTING SourceState = 2
	SourceState_SOURCE_STATE_FAULT    SourceState = 3
	// Safety check, pump laser, TEC bring-up, thermistor verification.
	SourceState_SOURCE_STATE_INITIALIZING SourceState = 4
	// Temperature sweep and resonance-dip acquisition.  Multi-minute.
	SourceState_SOURCE_STATE_LOCKING SourceState = 5
	// All loops locked, ready to be bound to a run via StartEmission.
	SourceState_SOURCE_STATE_READY SourceState = 6
	// Emitting, but at least one loop is outside tolerance.
	SourceState_SOURCE_STATE_DEGRADED       SourceState = 7
	SourceState_SOURCE_STATE_DEINITIALIZING SourceState = 8
)

// Enum value maps for SourceState.
var (
	SourceState_name = map[int32]string{
		0: "SOURCE_STATE_UNSPECIFIED",
		1: "SOURCE_STATE_IDLE",
		2: "SOURCE_STATE_EMITTING",
		3: "SOURCE_STATE_FAULT",
		4: "SOURCE_STATE_INITIALIZING",
		5: "SOURCE_STATE_LOCKING",
		6: "SOURCE_STATE_READY",
		7: "SOURCE_STATE_DEGRADED",
		8: "SOURCE_STATE_DEINITIALIZING",
	}
	SourceState_value = map[string]int32{
		"SOURCE_STATE_UNSPECIFIED":    0,
		"SOURCE_STATE_IDLE":           1,
		"SOURCE_STATE_EMITTING":       2,
		"SOURCE_STATE_FAULT":          3,
		"SOURCE_STATE_INITIALIZING":   4,
		"SOURCE_STATE_LOCKING":        5,
		"SOURCE_STATE_READY":          6,
		"SOURCE_STATE_DEGRADED":       7,
		"SOURCE_STATE_DEINITIALIZING": 8,
	}
)

func (x SourceState) Enum() *SourceState {
	p := new(SourceState)
	*p = x
	return p
}

func (x SourceState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SourceState) Descriptor() protoreflect.EnumDescriptor {
	return file_hal_adapters_source_v1_source_proto_enumTypes[0].Descriptor()
}

func (SourceState) Type() protoreflect.EnumType {
	return &file_hal_adapters_source_v1_source_proto_enumTypes[0]
}

func (x SourceState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SourceState.Descriptor instead.
func (SourceState) EnumDescriptor() ([]byte, []int) {
	return file_hal_adapters_source_v1_source_proto_rawDescGZIP(), []int{0}
}

type GetProductInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ResourceType  string                 `protobuf:"bytes,2,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductInfoRequest) Reset() {
	*x = GetProductInfoRequest{}
	mi := &file_hal_adapters_source_v1_source_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductInfoRequest) ProtoMessage() {}

func (x *GetProductInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_source_v1_source_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductInfoRequest.ProtoReflect.Descriptor instead.
func (*GetProductInfoRequest) Descriptor() ([]byte, []int) {
	return file_hal_adapters_source_v1_source_proto_rawDescGZIP(), []int{0}
}

func (x *GetProductInfoRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *GetProductInfoRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

type GetProductInfoResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SerialNumber    string                 `protobuf:"bytes,1,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	ProductCode     string                 `protobuf:"bytes,2,opt,name=product_code,json=productCode,proto3" json:"product_code,omitempty"`
	SoftwareVersion string                 `protobuf:"bytes,3,opt,name=software_version,json=softwareVersion,proto3" json:"software_version,omitempty"`
	Vendor          string                 `protobuf:"bytes,4,opt,name=vendor,proto3" json:"vendor,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetProductInfoResponse) Reset() {
	*x = GetProductInfoResponse{}
	mi := &file_hal_adapters_source_v1_source_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductInfoResponse) ProtoMessage() {}

func (x *GetProductInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_source_v1_source_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductInfoResponse.ProtoReflect.Descriptor instead.
func (*GetProductInfoResponse) Descriptor() ([]byte, []int) {
	return file_hal_adapters_source_v1_source_proto_rawDescGZIP(), []int{1}
}

func (x *GetProductInfoResponse) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *GetProductInfoResponse) GetProductCode() string {
	if x != nil {
		return x.ProductCode
	}
	return ""
}

func (x *GetProductInfoResponse) GetSoftwareVersion() string {
	if x != nil {
		return x.SoftwareVersion
	}
	return ""
}

func (x *GetProductInfoResponse) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

// Vendor-specific operating configuration (pump power, temperature
// setpoint, laser locking parameters, wavelength tuning, etc. -- whatever a
// given product needs). This spec doesn't model those fields: each
// product's adapter implementation defines and documents its own JSON
// schema for config_json and is responsible for parsing it. Neither the
// controller nor this spec validates or interprets its contents.
type SourceConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigJson    string                 `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SourceConfig) Reset() {
	*x = SourceConfig{}
	mi := &file_hal_adapters_source_v1_source_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SourceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SourceConfig) ProtoMessage() {}

func (x *SourceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_source_v1_source_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SourceConfig.ProtoReflect.Descriptor instead.
func (*SourceConfig) Descriptor() ([]byte, []int) {
	return file_hal_adapters_source_v1_source_proto_rawDescGZIP(), []int{2}
}

func (x *SourceConfig) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

type InitializeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Config        *SourceConfig          `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	ResourceType  string                 `protobuf:"bytes,3,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeRequest) Reset() {
	*x = InitializeRequest{}
	mi := &file_hal_adapters_source_v1_source_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeRequest) ProtoMessage() {}

func (x *InitializeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_source_v1_source_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeRequest.ProtoReflect.Descriptor instead.
func (*InitializeRequest) Descriptor() ([]byte, []int) {
	return file_hal_adapters_source_v1_source_proto_rawDescGZIP(), []int{3}
}

func (x *InitializeRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *InitializeRequest) GetConfig() *SourceConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *InitializeRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

type InitializeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeResponse) Reset() {
	*x = InitializeResponse{}
	mi := &file_hal_adapters_source_v1_source_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeResponse) ProtoMessage() {}

func (x *InitializeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_source_v1_source_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeResponse.ProtoReflect.Descriptor instead.
func (*InitializeResponse) Descriptor() ([]byte, []int) {
	return file_hal_adapters_source_v1_source_proto_rawDescGZIP(), []int{4}
}

func (x *InitializeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeinitializeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ResourceType  string                 `protobuf:"bytes,2,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeinitializeRequest) Reset() {
	*x = DeinitializeRequest{}
	mi := &file_hal_adapters_source_v1_source_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeinitializeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeinitializeRequest) ProtoMessage() {}

func (x *DeinitializeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_source_v1_source_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeinitializeRequest.ProtoReflect.Descriptor instead.
func (*DeinitializeRequest) Descriptor() ([]byte, []int) {
	return file_hal_adapters_source_v1_source_proto_rawDescGZIP(), []int{5}
}

func (x *DeinitializeRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *DeinitializeRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

type DeinitializeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeinitializeResponse) Reset() {
	*x = DeinitializeResponse{}
	mi := &file_hal_adapters_source_v1_source_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeinitializeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeinitializeResponse) ProtoMessage() {}

func (x *DeinitializeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_source_v1_source_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeinitializeResponse.ProtoReflect.Descriptor instead.
func (*DeinitializeResponse) Descriptor() ([]byte, []int) {
	return file_hal_adapters_source_v1_source_proto_rawDescGZIP(), []int{6}
}

func (x *DeinitializeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ResourceType  string                 `protobuf:"bytes,2,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_hal_adapters_source_v1_source_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_source_v1_source_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_hal_adapters_source_v1_source_proto_rawDescGZIP(), []int{7}
}

func (x *GetStatusRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *GetStatusRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         SourceState            `protobuf:"varint,1,opt,name=state,proto3,enum=hal.adapters.source.v1.SourceState" json:"state,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	UptimeSeconds float32                `protobuf:"fixed32,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	// Vendor-specific status detail (e.g. pump laser on/off, temperature-lock
	// state, per-loop tolerances, etc.) -- whatever a given product exposes
	// beyond the common SourceState. Encoded as a JSON object; each product's
	// adapter implementation defines and documents its own schema for it.
	StatusJson    string `protobuf:"bytes,4,opt,name=status_json,json=statusJson,proto3" json:"status_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_hal_adapters_source_v1_source_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_source_v1_source_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_hal_adapters_source_v1_source_proto_rawDescGZIP(), []int{8}
}

func (x *GetStatusResponse) GetState() SourceState {
	if x != nil {
		return x.State
	}
	return SourceState_SOURCE_STATE_UNSPECIFIED
}

func (x *GetStatusResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *GetStatusResponse) GetUptimeSeconds() float32 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *GetStatusResponse) GetStatusJson() string {
	if x != nil {
		return x.StatusJson
	}
	return ""
}

type SetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Config        *SourceConfig          `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	ResourceType  string                 `protobuf:"bytes,3,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConfigRequest) Reset() {
	*x = SetConfigRequest{}
	mi := &file_hal_adapters_source_v1_source_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConfigRequest) ProtoMessage() {}

func (x *SetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_source_v1_source_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConfigRequest.ProtoReflect.Descriptor instead.
func (*SetConfigRequest) Descriptor() ([]byte, []int) {
	return file_hal_adapters_source_v1_source_proto_rawDescGZIP(), []int{9}
}

func (x *SetConfigRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *SetConfigRequest) GetConfig() *SourceConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *SetConfigRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

type SetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConfigResponse) Reset() {
	*x = SetConfigResponse{}
	mi := &file_hal_adapters_source_v1_source_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConfigResponse) ProtoMessage() {}

func (x *SetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_source_v1_source_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConfigResponse.ProtoReflect.Descriptor instead.
func (*SetConfigResponse) Descriptor() ([]byte, []int) {
	return file_hal_adapters_source_v1_source_proto_rawDescGZIP(), []int{10}
}

func (x *SetConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StartEmissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Config        *SourceConfig          `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	ResourceType  string                 `protobuf:"bytes,4,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartEmissionRequest) Reset() {
	*x = StartEmissionRequest{}
	mi := &file_hal_adapters_source_v1_source_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartEmissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartEmissionRequest) ProtoMessage() {}

func (x *StartEmissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_source_v1_source_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartEmissionRequest.ProtoReflect.Descriptor instead.
func (*StartEmissionRequest) Descriptor() ([]byte, []int) {
	return file_hal_adapters_source_v1_source_proto_rawDescGZIP(), []int{11}
}

func (x *StartEmissionRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *StartEmissionRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *StartEmissionRequest) GetConfig() *SourceConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *StartEmissionRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

type StartEmissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartEmissionResponse) Reset() {
	*x = StartEmissionResponse{}
	mi := &file_hal_adapters_source_v1_source_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartEmissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartEmissionResponse) ProtoMessage() {}

func (x *StartEmissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_source_v1_source_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartEmissionResponse.ProtoReflect.Descriptor instead.
func (*StartEmissionResponse) Descriptor() ([]byte, []int) {
	return file_hal_adapters_source_v1_source_proto_rawDescGZIP(), []int{12}
}

func (x *StartEmissionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StopEmissionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	ResourceType  string                 `protobuf:"bytes,3,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopEmissionRequest) Reset() {
	*x = StopEmissionRequest{}
	mi := &file_hal_adapters_source_v1_source_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopEmissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopEmissionRequest) ProtoMessage() {}

func (x *StopEmissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_source_v1_source_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopEmissionRequest.ProtoReflect.Descriptor instead.
func (*StopEmissionRequest) Descriptor() ([]byte, []int) {
	return file_hal_adapters_source_v1_source_proto_rawDescGZIP(), []int{13}
}

func (x *StopEmissionRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *StopEmissionRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *StopEmissionRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

type StopEmissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopEmissionResponse) Reset() {
	*x = StopEmissionResponse{}
	mi := &file_hal_adapters_source_v1_source_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopEmissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopEmissionResponse) ProtoMessage() {}

func (x *StopEmissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_source_v1_source_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopEmissionResponse.ProtoReflect.Descriptor instead.
func (*StopEmissionResponse) Descriptor() ([]byte, []int) {
	return file_hal_adapters_source_v1_source_proto_rawDescGZIP(), []int{14}
}

func (x *StopEmissionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// event_type names which action to trigger (e.g. "fault", "perturbation",
// or anything else a product needs mid-run) -- adapter- and
// product-defined, not enumerated here. payload_json carries whatever
// parameters that action needs, encoded as a JSON object, per a schema the
// adapter implementation defines and documents for that event_type.
type TriggerEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,4,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	ResourceType  string                 `protobuf:"bytes,5,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerEventRequest) Reset() {
	*x = TriggerEventRequest{}
	mi := &file_hal_adapters_source_v1_source_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerEventRequest) ProtoMessage() {}

func (x *TriggerEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_source_v1_source_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerEventRequest.ProtoReflect.Descriptor instead.
func (*TriggerEventRequest) Descriptor() ([]byte, []int) {
	return file_hal_adapters_source_v1_source_proto_rawDescGZIP(), []int{15}
}

func (x *TriggerEventRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *TriggerEventRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *TriggerEventRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *TriggerEventRequest) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

func (x *TriggerEventRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

type TriggerEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerEventResponse) Reset() {
	*x = TriggerEventResponse{}
	mi := &file_hal_adapters_source_v1_source_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerEventResponse) ProtoMessage() {}

func (x *TriggerEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_source_v1_source_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerEventResponse.ProtoReflect.Descriptor instead.
func (*TriggerEventResponse) Descriptor() ([]byte, []int) {
	return file_hal_adapters_source_v1_source_proto_rawDescGZIP(), []int{16}
}

func (x *TriggerEventResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_hal_adapters_source_v1_source_proto protoreflect.FileDescriptor

const file_hal_adapters_source_v1_source_proto_rawDesc = "" +
	"\n" +
	"#hal/adapters/source/v1/source.proto\x12\x16hal.adapters.source.v1\x1a#hal/adapters/common/v1/common.proto\"[\n" +
	"\x15GetProductInfoRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12#\n" +
	"\rresource_type\x18\x02 \x01(\tR\fresourceType\"\xa3\x01\n" +
	"\x16GetProductInfoResponse\x12#\n" +
	"\rserial_number\x18\x01 \x01(\tR\fserialNumber\x12!\n" +
	"\fproduct_code\x18\x02 \x01(\tR\vproductCode\x12)\n" +
	"\x10software_version\x18\x03 \x01(\tR\x0fsoftwareVersion\x12\x16\n" +
	"\x06vendor\x18\x04 \x01(\tR\x06vendor\"/\n" +
	"\fSourceConfig\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\tR\n" +
	"configJson\"\x95\x01\n" +
	"\x11InitializeRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12<\n" +
	"\x06config\x18\x02 \x01(\v2$.hal.adapters.source.v1.SourceConfigR\x06config\x12#\n" +
	"\rresource_type\x18\x03 \x01(\tR\fresourceType\".\n" +
	"\x12InitializeResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"Y\n" +
	"\x13DeinitializeRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12#\n" +
	"\rresource_type\x18\x02 \x01(\tR\fresourceType\"0\n" +
	"\x14DeinitializeResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"V\n" +
	"\x10GetStatusRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12#\n" +
	"\rresource_type\x18\x02 \x01(\tR\fresourceType\"\xad\x01\n" +
	"\x11GetStatusResponse\x129\n" +
	"\x05state\x18\x01 \x01(\x0e2#.hal.adapters.source.v1.SourceStateR\x05state\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x02R\ruptimeSeconds\x12\x1f\n" +
	"\vstatus_json\x18\x04 \x01(\tR\n" +
	"statusJson\"\x94\x01\n" +
	"\x10SetConfigRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12<\n" +
	"\x06config\x18\x02 \x01(\v2$.hal.adapters.source.v1.SourceConfigR\x06config\x12#\n" +
	"\rresource_type\x18\x03 \x01(\tR\fresourceType\"-\n" +
	"\x11SetConfigResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xaf\x01\n" +
	"\x14StartEmissionRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12<\n" +
	"\x06config\x18\x03 \x01(\v2$.hal.adapters.source.v1.SourceConfigR\x06config\x12#\n" +
	"\rresource_type\x18\x04 \x01(\tR\fresourceType\"1\n" +
	"\x15StartEmissionResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"p\n" +
	"\x13StopEmissionRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12#\n" +
	"\rresource_type\x18\x03 \x01(\tR\fresourceType\"0\n" +
	"\x14StopEmissionResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xb2\x01\n" +
	"\x13TriggerEventRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12!\n" +
	"\fpayload_json\x18\x04 \x01(\tR\vpayloadJson\x12#\n" +
	"\rresource_type\x18\x05 \x01(\tR\fresourceType\"0\n" +
	"\x14TriggerEventResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage*\x82\x02\n" +
	"\vSourceState\x12\x1c\n" +
	"\x18SOURCE_STATE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11SOURCE_STATE_IDLE\x10\x01\x12\x19\n" +
	"\x15SOURCE_STATE_EMITTING\x10\x02\x12\x16\n" +
	"\x12SOURCE_STATE_FAULT\x10\x03\x12\x1d\n" +
	"\x19SOURCE_STATE_INITIALIZING\x10\x04\x12\x18\n" +
	"\x14SOURCE_STATE_LOCKING\x10\x05\x12\x16\n" +
	"\x12SOURCE_STATE_READY\x10\x06\x12\x19\n" +
	"\x15SOURCE_STATE_DEGRADED\x10\a\x12\x1f\n" +
	"\x1bSOURCE_STATE_DEINITIALIZING\x10\b2\x82\n" +
	"\n" +
	"\x14AdapterSourceService\x12f\n" +
	"\vHealthCheck\x12*.hal.adapters.common.v1.HealthCheckRequest\x1a+.hal.adapters.common.v1.HealthCheckResponse\x12~\n" +
	"\x13ResourceHealthCheck\x122.hal.adapters.common.v1.ResourceHealthCheckRequest\x1a3.hal.adapters.common.v1.ResourceHealthCheckResponse\x12o\n" +
	"\x0eGetProductInfo\x12-.hal.adapters.source.v1.GetProductInfoRequest\x1a..hal.adapters.source.v1.GetProductInfoResponse\x12c\n" +
	"\n" +
	"Initialize\x12).hal.adapters.source.v1.InitializeRequest\x1a*.hal.adapters.source.v1.InitializeResponse\x12i\n" +
	"\fDeinitialize\x12+.hal.adapters.source.v1.DeinitializeRequest\x1a,.hal.adapters.source.v1.DeinitializeResponse\x12`\n" +
	"\tGetStatus\x12(.hal.adapters.source.v1.GetStatusRequest\x1a).hal.adapters.source.v1.GetStatusResponse\x12`\n" +
	"\tSetConfig\x12(.hal.adapters.source.v1.SetConfigRequest\x1a).hal.adapters.source.v1.SetConfigResponse\x12f\n" +
	"\vAutoRecover\x12*.hal.adapters.common.v1.AutoRecoverRequest\x1a+.hal.adapters.common.v1.AutoRecoverResponse\x12Q\n" +
	"\x04Tune\x12#.hal.adapters.common.v1.TuneRequest\x1a$.hal.adapters.common.v1.TuneResponse\x12l\n" +
	"\rStartEmission\x12,.hal.adapters.source.v1.StartEmissionRequest\x1a-.hal.adapters.source.v1.StartEmissionResponse\x12i\n" +
	"\fStopEmission\x12+.hal.adapters.source.v1.StopEmissionRequest\x1a,.hal.adapters.source.v1.StopEmissionResponse\x12i\n" +
	"\fTriggerEvent\x12+.hal.adapters.source.v1.TriggerEventRequest\x1a,.hal.adapters.source.v1.TriggerEventResponseB\xf1\x01\n" +
	"\x1acom.hal.adapters.source.v1B\vSourceProtoP\x01ZKgithub.com/outshift-open/quantum-hal/sdk/go/hal/adapters/source/v1;sourcev1\xa2\x02\x03HAS\xaa\x02\x16Hal.Adapters.Source.V1\xca\x02\x16Hal\\Adapters\\Source\\V1\xe2\x02\"Hal\\Adapters\\Source\\V1\\GPBMetadata\xea\x02\x19Hal::Adapters::Source::V1b\x06proto3"

var (
	file_hal_adapters_source_v1_source_proto_rawDescOnce sync.Once
	file_hal_adapters_source_v1_source_proto_rawDescData []byte
)

func file_hal_adapters_source_v1_source_proto_rawDescGZIP() []byte {
	file_hal_adapters_source_v1_source_proto_rawDescOnce.Do(func() {
		file_hal_adapters_source_v1_source_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hal_adapters_source_v1_source_proto_rawDesc), len(file_hal_adapters_source_v1_source_proto_rawDesc)))
	})
	return file_hal_adapters_source_v1_source_proto_rawDescData
}

var file_hal_adapters_source_v1_source_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_hal_adapters_source_v1_source_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_hal_adapters_source_v1_source_proto_goTypes = []any{
	(SourceState)(0),                       // 0: hal.adapters.source.v1.SourceState
	(*GetProductInfoRequest)(nil),          // 1: hal.adapters.source.v1.GetProductInfoRequest
	(*GetProductInfoResponse)(nil),         // 2: hal.adapters.source.v1.GetProductInfoResponse
	(*SourceConfig)(nil),                   // 3: hal.adapters.source.v1.SourceConfig
	(*InitializeRequest)(nil),              // 4: hal.adapters.source.v1.InitializeRequest
	(*InitializeResponse)(nil),             // 5: hal.adapters.source.v1.InitializeResponse
	(*DeinitializeRequest)(nil),            // 6: hal.adapters.source.v1.DeinitializeRequest
	(*DeinitializeResponse)(nil),           // 7: hal.adapters.source.v1.DeinitializeResponse
	(*GetStatusRequest)(nil),               // 8: hal.adapters.source.v1.GetStatusRequest
	(*GetStatusResponse)(nil),              // 9: hal.adapters.source.v1.GetStatusResponse
	(*SetConfigRequest)(nil),               // 10: hal.adapters.source.v1.SetConfigRequest
	(*SetConfigResponse)(nil),              // 11: hal.adapters.source.v1.SetConfigResponse
	(*StartEmissionRequest)(nil),           // 12: hal.adapters.source.v1.StartEmissionRequest
	(*StartEmissionResponse)(nil),          // 13: hal.adapters.source.v1.StartEmissionResponse
	(*StopEmissionRequest)(nil),            // 14: hal.adapters.source.v1.StopEmissionRequest
	(*StopEmissionResponse)(nil),           // 15: hal.adapters.source.v1.StopEmissionResponse
	(*TriggerEventRequest)(nil),            // 16: hal.adapters.source.v1.TriggerEventRequest
	(*TriggerEventResponse)(nil),           // 17: hal.adapters.source.v1.TriggerEventResponse
	(*v1.HealthCheckRequest)(nil),          // 18: hal.adapters.common.v1.HealthCheckRequest
	(*v1.ResourceHealthCheckRequest)(nil),  // 19: hal.adapters.common.v1.ResourceHealthCheckRequest
	(*v1.AutoRecoverRequest)(nil),          // 20: hal.adapters.common.v1.AutoRecoverRequest
	(*v1.TuneRequest)(nil),                 // 21: hal.adapters.common.v1.TuneRequest
	(*v1.HealthCheckResponse)(nil),         // 22: hal.adapters.common.v1.HealthCheckResponse
	(*v1.ResourceHealthCheckResponse)(nil), // 23: hal.adapters.common.v1.ResourceHealthCheckResponse
	(*v1.AutoRecoverResponse)(nil),         // 24: hal.adapters.common.v1.AutoRecoverResponse
	(*v1.TuneResponse)(nil),                // 25: hal.adapters.common.v1.TuneResponse
}
var file_hal_adapters_source_v1_source_proto_depIdxs = []int32{
	3,  // 0: hal.adapters.source.v1.InitializeRequest.config:type_name -> hal.adapters.source.v1.SourceConfig
	0,  // 1: hal.adapters.source.v1.GetStatusResponse.state:type_name -> hal.adapters.source.v1.SourceState
	3,  // 2: hal.adapters.source.v1.SetConfigRequest.config:type_name -> hal.adapters.source.v1.SourceConfig
	3,  // 3: hal.adapters.source.v1.StartEmissionRequest.config:type_name -> hal.adapters.source.v1.SourceConfig
	18, // 4: hal.adapters.source.v1.AdapterSourceService.HealthCheck:input_type -> hal.adapters.common.v1.HealthCheckRequest
	19, // 5: hal.adapters.source.v1.AdapterSourceService.ResourceHealthCheck:input_type -> hal.adapters.common.v1.ResourceHealthCheckRequest
	1,  // 6: hal.adapters.source.v1.AdapterSourceService.GetProductInfo:input_type -> hal.adapters.source.v1.GetProductInfoRequest
	4,  // 7: hal.adapters.source.v1.AdapterSourceService.Initialize:input_type -> hal.adapters.source.v1.InitializeRequest
	6,  // 8: hal.adapters.source.v1.AdapterSourceService.Deinitialize:input_type -> hal.adapters.source.v1.DeinitializeRequest
	8,  // 9: hal.adapters.source.v1.AdapterSourceService.GetStatus:input_type -> hal.adapters.source.v1.GetStatusRequest
	10, // 10: hal.adapters.source.v1.AdapterSourceService.SetConfig:input_type -> hal.adapters.source.v1.SetConfigRequest
	20, // 11: hal.adapters.source.v1.AdapterSourceService.AutoRecover:input_type -> hal.adapters.common.v1.AutoRecoverRequest
	21, // 12: hal.adapters.source.v1.AdapterSourceService.Tune:input_type -> hal.adapters.common.v1.TuneRequest
	12, // 13: hal.adapters.source.v1.AdapterSourceService.StartEmission:input_type -> hal.adapters.source.v1.StartEmissionRequest
	14, // 14: hal.adapters.source.v1.AdapterSourceService.StopEmission:input_type -> hal.adapters.source.v1.StopEmissionRequest
	16, // 15: hal.adapters.source.v1.AdapterSourceService.TriggerEvent:input_type -> hal.adapters.source.v1.TriggerEventRequest
	22, // 16: hal.adapters.source.v1.AdapterSourceService.HealthCheck:output_type -> hal.adapters.common.v1.HealthCheckResponse
	23, // 17: hal.adapters.source.v1.AdapterSourceService.ResourceHealthCheck:output_type -> hal.adapters.common.v1.ResourceHealthCheckResponse
	2,  // 18: hal.adapters.source.v1.AdapterSourceService.GetProductInfo:output_type -> hal.adapters.source.v1.GetProductInfoResponse
	5,  // 19: hal.adapters.source.v1.AdapterSourceService.Initialize:output_type -> hal.adapters.source.v1.InitializeResponse
	7,  // 20: hal.adapters.source.v1.AdapterSourceService.Deinitialize:output_type -> hal.adapters.source.v1.DeinitializeResponse
	9,  // 21: hal.adapters.source.v1.AdapterSourceService.GetStatus:output_type -> hal.adapters.source.v1.GetStatusResponse
	11, // 22: hal.adapters.source.v1.AdapterSourceService.SetConfig:output_type -> hal.adapters.source.v1.SetConfigResponse
	24, // 23: hal.adapters.source.v1.AdapterSourceService.AutoRecover:output_type -> hal.adapters.common.v1.AutoRecoverResponse
	25, // 24: hal.adapters.source.v1.AdapterSourceService.Tune:output_type -> hal.adapters.common.v1.TuneResponse
	13, // 25: hal.adapters.source.v1.AdapterSourceService.StartEmission:output_type -> hal.adapters.source.v1.StartEmissionResponse
	15, // 26: hal.adapters.source.v1.AdapterSourceService.StopEmission:output_type -> hal.adapters.source.v1.StopEmissionResponse
	17, // 27: hal.adapters.source.v1.AdapterSourceService.TriggerEvent:output_type -> hal.adapters.source.v1.TriggerEventResponse
	16, // [16:28] is the sub-list for method output_type
	4,  // [4:16] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_hal_adapters_source_v1_source_proto_init() }
func file_hal_adapters_source_v1_source_proto_init() {
	if File_hal_adapters_source_v1_source_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hal_adapters_source_v1_source_proto_rawDesc), len(file_hal_adapters_source_v1_source_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hal_adapters_source_v1_source_proto_goTypes,
		DependencyIndexes: file_hal_adapters_source_v1_source_proto_depIdxs,
		EnumInfos:         file_hal_adapters_source_v1_source_proto_enumTypes,
		MessageInfos:      file_hal_adapters_source_v1_source_proto_msgTypes,
	}.Build()
	File_hal_adapters_source_v1_source_proto = out.File
	file_hal_adapters_source_v1_source_proto_goTypes = nil
	file_hal_adapters_source_v1_source_proto_depIdxs = nil
}
