// Copyright 2026 Cisco Systems, Inc. and its affiliates
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: hal/adapters/source/v1/source.proto

package sourcev1

import (
	context "context"
	v1 "github.com/outshift-open/quantum-hal/sdk/go/hal/adapters/common/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdapterSourceService_HealthCheck_FullMethodName         = "/hal.adapters.source.v1.AdapterSourceService/HealthCheck"
	AdapterSourceService_ResourceHealthCheck_FullMethodName = "/hal.adapters.source.v1.AdapterSourceService/ResourceHealthCheck"
	AdapterSourceService_GetProductInfo_FullMethodName      = "/hal.adapters.source.v1.AdapterSourceService/GetProductInfo"
	AdapterSourceService_Initialize_FullMethodName          = "/hal.adapters.source.v1.AdapterSourceService/Initialize"
	AdapterSourceService_Deinitialize_FullMethodName        = "/hal.adapters.source.v1.AdapterSourceService/Deinitialize"
	AdapterSourceService_GetStatus_FullMethodName           = "/hal.adapters.source.v1.AdapterSourceService/GetStatus"
	AdapterSourceService_SetConfig_FullMethodName           = "/hal.adapters.source.v1.AdapterSourceService/SetConfig"
	AdapterSourceService_AutoRecover_FullMethodName         = "/hal.adapters.source.v1.AdapterSourceService/AutoRecover"
	AdapterSourceService_Tune_FullMethodName                = "/hal.adapters.source.v1.AdapterSourceService/Tune"
	AdapterSourceService_StartEmission_FullMethodName       = "/hal.adapters.source.v1.AdapterSourceService/StartEmission"
	AdapterSourceService_StopEmission_FullMethodName        = "/hal.adapters.source.v1.AdapterSourceService/StopEmission"
	AdapterSourceService_TriggerEvent_FullMethodName        = "/hal.adapters.source.v1.AdapterSourceService/TriggerEvent"
)

// AdapterSourceServiceClient is the client API for AdapterSourceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdapterSourceServiceClient interface {
	// Liveness of the adapter process itself. See common.proto.
	HealthCheck(ctx context.Context, in *v1.HealthCheckRequest, opts ...grpc.CallOption) (*v1.HealthCheckResponse, error)
	// Health of the physical source hardware behind the adapter. See
	// common.proto; the UP / DOWN / DEGRADED-style result may be informed by
	// the device's current SourceState.
	ResourceHealthCheck(ctx context.Context, in *v1.ResourceHealthCheckRequest, opts ...grpc.CallOption) (*v1.ResourceHealthCheckResponse, error)
	// Static identity of the hardware behind the adapter: serial number,
	// vendor, firmware/software version.
	GetProductInfo(ctx context.Context, in *GetProductInfoRequest, opts ...grpc.CallOption) (*GetProductInfoResponse, error)
	// Brings the source from a freshly power-cycled state to
	// SOURCE_STATE_READY: applies the operating configuration (pump power,
	// temperature/TEC setpoint, laser locking, etc.) and runs whatever
	// bring-up sequence the hardware needs. Returns as soon as the sequence
	// is accepted -- bring-up can take minutes and cannot sit inside a call
	// the caller has a deadline on -- so callers poll GetStatus until the
	// state reaches READY or FAULT.
	Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*InitializeResponse, error)
	// The opposite of Initialize: orderly shutdown once all jobs are done --
	// turns off the pump laser and de-energizes whatever else Initialize
	// brought up -- back toward SOURCE_STATE_IDLE.
	Deinitialize(ctx context.Context, in *DeinitializeRequest, opts ...grpc.CallOption) (*DeinitializeResponse, error)
	// Current lifecycle state and health of the source, plus which run (if
	// any) it is bound to. Poll this after Initialize/Deinitialize, and
	// during emission.
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	// Updates the source's operating configuration without a full
	// Initialize/Deinitialize cycle.
	SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*SetConfigResponse, error)
	// Attempts the adapter's built-in automated recovery sequence to bring
	// the source back from SOURCE_STATE_DEGRADED (or FAULT) toward READY --
	// e.g. re-running the resonance lock, restarting the pump laser, or
	// whatever vendor-specific remediation applies. See common.proto. Returns
	// as soon as the sequence is accepted -- recovery can take as long as
	// Initialize -- so callers poll GetStatus for the outcome.
	AutoRecover(ctx context.Context, in *v1.AutoRecoverRequest, opts ...grpc.CallOption) (*v1.AutoRecoverResponse, error)
	// Applies a single targeted adjustment as an alternative to a full
	// AutoRecover sequence -- e.g. nudge one setpoint rather than re-running
	// the whole remediation. See common.proto. Vendor-specific; adapters with
	// no such fine-grained control may return UNIMPLEMENTED.
	Tune(ctx context.Context, in *v1.TuneRequest, opts ...grpc.CallOption) (*v1.TuneResponse, error)
	// Starts generating entanglement pairs for the given run. Called when
	// the controller begins a job -- e.g. an entanglement-distribution
	// intent between two endpoints. Requires SOURCE_STATE_READY; moves the
	// source into SOURCE_STATE_EMITTING for the duration of the run.
	StartEmission(ctx context.Context, in *StartEmissionRequest, opts ...grpc.CallOption) (*StartEmissionResponse, error)
	// Stops generating entanglement pairs and returns the source to
	// SOURCE_STATE_READY, available for the next job.
	StopEmission(ctx context.Context, in *StopEmissionRequest, opts ...grpc.CallOption) (*StopEmissionResponse, error)
	// Triggers a special, adapter-defined action for a running job -- not
	// limited to fault/emulation scenarios (e.g. an induced fault or an
	// environmental perturbation for testing); anything else the device
	// might need done mid-run that doesn't fit the RPCs above. Optional: an
	// adapter with no such capability may return UNIMPLEMENTED.
	TriggerEvent(ctx context.Context, in *TriggerEventRequest, opts ...grpc.CallOption) (*TriggerEventResponse, error)
}

type adapterSourceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdapterSourceServiceClient(cc grpc.ClientConnInterface) AdapterSourceServiceClient {
	return &adapterSourceServiceClient{cc}
}

func (c *adapterSourceServiceClient) HealthCheck(ctx context.Context, in *v1.HealthCheckRequest, opts ...grpc.CallOption) (*v1.HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.HealthCheckResponse)
	err := c.cc.Invoke(ctx, AdapterSourceService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterSourceServiceClient) ResourceHealthCheck(ctx context.Context, in *v1.ResourceHealthCheckRequest, opts ...grpc.CallOption) (*v1.ResourceHealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.ResourceHealthCheckResponse)
	err := c.cc.Invoke(ctx, AdapterSourceService_ResourceHealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterSourceServiceClient) GetProductInfo(ctx context.Context, in *GetProductInfoRequest, opts ...grpc.CallOption) (*GetProductInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductInfoResponse)
	err := c.cc.Invoke(ctx, AdapterSourceService_GetProductInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterSourceServiceClient) Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*InitializeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitializeResponse)
	err := c.cc.Invoke(ctx, AdapterSourceService_Initialize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterSourceServiceClient) Deinitialize(ctx context.Context, in *DeinitializeRequest, opts ...grpc.CallOption) (*DeinitializeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeinitializeResponse)
	err := c.cc.Invoke(ctx, AdapterSourceService_Deinitialize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterSourceServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, AdapterSourceService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterSourceServiceClient) SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*SetConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetConfigResponse)
	err := c.cc.Invoke(ctx, AdapterSourceService_SetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterSourceServiceClient) AutoRecover(ctx context.Context, in *v1.AutoRecoverRequest, opts ...grpc.CallOption) (*v1.AutoRecoverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.AutoRecoverResponse)
	err := c.cc.Invoke(ctx, AdapterSourceService_AutoRecover_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterSourceServiceClient) Tune(ctx context.Context, in *v1.TuneRequest, opts ...grpc.CallOption) (*v1.TuneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.TuneResponse)
	err := c.cc.Invoke(ctx, AdapterSourceService_Tune_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterSourceServiceClient) StartEmission(ctx context.Context, in *StartEmissionRequest, opts ...grpc.CallOption) (*StartEmissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartEmissionResponse)
	err := c.cc.Invoke(ctx, AdapterSourceService_StartEmission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterSourceServiceClient) StopEmission(ctx context.Context, in *StopEmissionRequest, opts ...grpc.CallOption) (*StopEmissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopEmissionResponse)
	err := c.cc.Invoke(ctx, AdapterSourceService_StopEmission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterSourceServiceClient) TriggerEvent(ctx context.Context, in *TriggerEventRequest, opts ...grpc.CallOption) (*TriggerEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerEventResponse)
	err := c.cc.Invoke(ctx, AdapterSourceService_TriggerEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdapterSourceServiceServer is the server API for AdapterSourceService service.
// All implementations must embed UnimplementedAdapterSourceServiceServer
// for forward compatibility.
type AdapterSourceServiceServer interface {
	// Liveness of the adapter process itself. See common.proto.
	HealthCheck(context.Context, *v1.HealthCheckRequest) (*v1.HealthCheckResponse, error)
	// Health of the physical source hardware behind the adapter. See
	// common.proto; the UP / DOWN / DEGRADED-style result may be informed by
	// the device's current SourceState.
	ResourceHealthCheck(context.Context, *v1.ResourceHealthCheckRequest) (*v1.ResourceHealthCheckResponse, error)
	// Static identity of the hardware behind the adapter: serial number,
	// vendor, firmware/software version.
	GetProductInfo(context.Context, *GetProductInfoRequest) (*GetProductInfoResponse, error)
	// Brings the source from a freshly power-cycled state to
	// SOURCE_STATE_READY: applies the operating configuration (pump power,
	// temperature/TEC setpoint, laser locking, etc.) and runs whatever
	// bring-up sequence the hardware needs. Returns as soon as the sequence
	// is accepted -- bring-up can take minutes and cannot sit inside a call
	// the caller has a deadline on -- so callers poll GetStatus until the
	// state reaches READY or FAULT.
	Initialize(context.Context, *InitializeRequest) (*InitializeResponse, error)
	// The opposite of Initialize: orderly shutdown once all jobs are done --
	// turns off the pump laser and de-energizes whatever else Initialize
	// brought up -- back toward SOURCE_STATE_IDLE.
	Deinitialize(context.Context, *DeinitializeRequest) (*DeinitializeResponse, error)
	// Current lifecycle state and health of the source, plus which run (if
	// any) it is bound to. Poll this after Initialize/Deinitialize, and
	// during emission.
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	// Updates the source's operating configuration without a full
	// Initialize/Deinitialize cycle.
	SetConfig(context.Context, *SetConfigRequest) (*SetConfigResponse, error)
	// Attempts the adapter's built-in automated recovery sequence to bring
	// the source back from SOURCE_STATE_DEGRADED (or FAULT) toward READY --
	// e.g. re-running the resonance lock, restarting the pump laser, or
	// whatever vendor-specific remediation applies. See common.proto. Returns
	// as soon as the sequence is accepted -- recovery can take as long as
	// Initialize -- so callers poll GetStatus for the outcome.
	AutoRecover(context.Context, *v1.AutoRecoverRequest) (*v1.AutoRecoverResponse, error)
	// Applies a single targeted adjustment as an alternative to a full
	// AutoRecover sequence -- e.g. nudge one setpoint rather than re-running
	// the whole remediation. See common.proto. Vendor-specific; adapters with
	// no such fine-grained control may return UNIMPLEMENTED.
	Tune(context.Context, *v1.TuneRequest) (*v1.TuneResponse, error)
	// Starts generating entanglement pairs for the given run. Called when
	// the controller begins a job -- e.g. an entanglement-distribution
	// intent between two endpoints. Requires SOURCE_STATE_READY; moves the
	// source into SOURCE_STATE_EMITTING for the duration of the run.
	StartEmission(context.Context, *StartEmissionRequest) (*StartEmissionResponse, error)
	// Stops generating entanglement pairs and returns the source to
	// SOURCE_STATE_READY, available for the next job.
	StopEmission(context.Context, *StopEmissionRequest) (*StopEmissionResponse, error)
	// Triggers a special, adapter-defined action for a running job -- not
	// limited to fault/emulation scenarios (e.g. an induced fault or an
	// environmental perturbation for testing); anything else the device
	// might need done mid-run that doesn't fit the RPCs above. Optional: an
	// adapter with no such capability may return UNIMPLEMENTED.
	TriggerEvent(context.Context, *TriggerEventRequest) (*TriggerEventResponse, error)
	mustEmbedUnimplementedAdapterSourceServiceServer()
}

// UnimplementedAdapterSourceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdapterSourceServiceServer struct{}

func (UnimplementedAdapterSourceServiceServer) HealthCheck(context.Context, *v1.HealthCheckRequest) (*v1.HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedAdapterSourceServiceServer) ResourceHealthCheck(context.Context, *v1.ResourceHealthCheckRequest) (*v1.ResourceHealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResourceHealthCheck not implemented")
}
func (UnimplementedAdapterSourceServiceServer) GetProductInfo(context.Context, *GetProductInfoRequest) (*GetProductInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProductInfo not implemented")
}
func (UnimplementedAdapterSourceServiceServer) Initialize(context.Context, *InitializeRequest) (*InitializeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Initialize not implemented")
}
func (UnimplementedAdapterSourceServiceServer) Deinitialize(context.Context, *DeinitializeRequest) (*DeinitializeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Deinitialize not implemented")
}
func (UnimplementedAdapterSourceServiceServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedAdapterSourceServiceServer) SetConfig(context.Context, *SetConfigRequest) (*SetConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetConfig not implemented")
}
func (UnimplementedAdapterSourceServiceServer) AutoRecover(context.Context, *v1.AutoRecoverRequest) (*v1.AutoRecoverResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AutoRecover not implemented")
}
func (UnimplementedAdapterSourceServiceServer) Tune(context.Context, *v1.TuneRequest) (*v1.TuneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Tune not implemented")
}
func (UnimplementedAdapterSourceServiceServer) StartEmission(context.Context, *StartEmissionRequest) (*StartEmissionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartEmission not implemented")
}
func (UnimplementedAdapterSourceServiceServer) StopEmission(context.Context, *StopEmissionRequest) (*StopEmissionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopEmission not implemented")
}
func (UnimplementedAdapterSourceServiceServer) TriggerEvent(context.Context, *TriggerEventRequest) (*TriggerEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerEvent not implemented")
}
func (UnimplementedAdapterSourceServiceServer) mustEmbedUnimplementedAdapterSourceServiceServer() {}
func (UnimplementedAdapterSourceServiceServer) testEmbeddedByValue()                              {}

// UnsafeAdapterSourceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdapterSourceServiceServer will
// result in compilation errors.
type UnsafeAdapterSourceServiceServer interface {
	mustEmbedUnimplementedAdapterSourceServiceServer()
}

func RegisterAdapterSourceServiceServer(s grpc.ServiceRegistrar, srv AdapterSourceServiceServer) {
	// If the following call panics, it indicates UnimplementedAdapterSourceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdapterSourceService_ServiceDesc, srv)
}

func _AdapterSourceService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterSourceServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterSourceService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterSourceServiceServer).HealthCheck(ctx, req.(*v1.HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterSourceService_ResourceHealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.ResourceHealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterSourceServiceServer).ResourceHealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterSourceService_ResourceHealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterSourceServiceServer).ResourceHealthCheck(ctx, req.(*v1.ResourceHealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterSourceService_GetProductInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterSourceServiceServer).GetProductInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterSourceService_GetProductInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterSourceServiceServer).GetProductInfo(ctx, req.(*GetProductInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterSourceService_Initialize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitializeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterSourceServiceServer).Initialize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterSourceService_Initialize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterSourceServiceServer).Initialize(ctx, req.(*InitializeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterSourceService_Deinitialize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeinitializeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterSourceServiceServer).Deinitialize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterSourceService_Deinitialize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterSourceServiceServer).Deinitialize(ctx, req.(*DeinitializeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterSourceService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterSourceServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterSourceService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterSourceServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterSourceService_SetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterSourceServiceServer).SetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterSourceService_SetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterSourceServiceServer).SetConfig(ctx, req.(*SetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterSourceService_AutoRecover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.AutoRecoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterSourceServiceServer).AutoRecover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterSourceService_AutoRecover_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterSourceServiceServer).AutoRecover(ctx, req.(*v1.AutoRecoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterSourceService_Tune_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.TuneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterSourceServiceServer).Tune(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterSourceService_Tune_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterSourceServiceServer).Tune(ctx, req.(*v1.TuneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterSourceService_StartEmission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartEmissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterSourceServiceServer).StartEmission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterSourceService_StartEmission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterSourceServiceServer).StartEmission(ctx, req.(*StartEmissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterSourceService_StopEmission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopEmissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterSourceServiceServer).StopEmission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterSourceService_StopEmission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterSourceServiceServer).StopEmission(ctx, req.(*StopEmissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterSourceService_TriggerEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterSourceServiceServer).TriggerEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterSourceService_TriggerEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterSourceServiceServer).TriggerEvent(ctx, req.(*TriggerEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdapterSourceService_ServiceDesc is the grpc.ServiceDesc for AdapterSourceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdapterSourceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hal.adapters.source.v1.AdapterSourceService",
	HandlerType: (*AdapterSourceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _AdapterSourceService_HealthCheck_Handler,
		},
		{
			MethodName: "ResourceHealthCheck",
			Handler:    _AdapterSourceService_ResourceHealthCheck_Handler,
		},
		{
			MethodName: "GetProductInfo",
			Handler:    _AdapterSourceService_GetProductInfo_Handler,
		},
		{
			MethodName: "Initialize",
			Handler:    _AdapterSourceService_Initialize_Handler,
		},
		{
			MethodName: "Deinitialize",
			Handler:    _AdapterSourceService_Deinitialize_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _AdapterSourceService_GetStatus_Handler,
		},
		{
			MethodName: "SetConfig",
			Handler:    _AdapterSourceService_SetConfig_Handler,
		},
		{
			MethodName: "AutoRecover",
			Handler:    _AdapterSourceService_AutoRecover_Handler,
		},
		{
			MethodName: "Tune",
			Handler:    _AdapterSourceService_Tune_Handler,
		},
		{
			MethodName: "StartEmission",
			Handler:    _AdapterSourceService_StartEmission_Handler,
		},
		{
			MethodName: "StopEmission",
			Handler:    _AdapterSourceService_StopEmission_Handler,
		},
		{
			MethodName: "TriggerEvent",
			Handler:    _AdapterSourceService_TriggerEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hal/adapters/source/v1/source.proto",
}
