# Copyright 2026 Cisco Systems, Inc. and its affiliates
#
# SPDX-License-Identifier: Apache-2.0

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from hal.adapters.common.v1 import common_pb2 as hal_dot_adapters_dot_common_dot_v1_dot_common__pb2
from hal.adapters.timetagger.v1 import timetagger_pb2 as hal_dot_adapters_dot_timetagger_dot_v1_dot_timetagger__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hal/adapters/timetagger/v1/timetagger_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AdapterTimeTaggerServiceStub:
    """--- Liveness & discovery ---
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/hal.adapters.timetagger.v1.AdapterTimeTaggerService/HealthCheck',
                request_serializer=hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.ResourceHealthCheck = channel.unary_unary(
                '/hal.adapters.timetagger.v1.AdapterTimeTaggerService/ResourceHealthCheck',
                request_serializer=hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.ResourceHealthCheckRequest.SerializeToString,
                response_deserializer=hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.ResourceHealthCheckResponse.FromString,
                _registered_method=True)
        self.GetProductInfo = channel.unary_unary(
                '/hal.adapters.timetagger.v1.AdapterTimeTaggerService/GetProductInfo',
                request_serializer=hal_dot_adapters_dot_timetagger_dot_v1_dot_timetagger__pb2.GetProductInfoRequest.SerializeToString,
                response_deserializer=hal_dot_adapters_dot_timetagger_dot_v1_dot_timetagger__pb2.GetProductInfoResponse.FromString,
                _registered_method=True)
        self.Initialize = channel.unary_unary(
                '/hal.adapters.timetagger.v1.AdapterTimeTaggerService/Initialize',
                request_serializer=hal_dot_adapters_dot_timetagger_dot_v1_dot_timetagger__pb2.InitializeRequest.SerializeToString,
                response_deserializer=hal_dot_adapters_dot_timetagger_dot_v1_dot_timetagger__pb2.InitializeResponse.FromString,
                _registered_method=True)
        self.Deinitialize = channel.unary_unary(
                '/hal.adapters.timetagger.v1.AdapterTimeTaggerService/Deinitialize',
                request_serializer=hal_dot_adapters_dot_timetagger_dot_v1_dot_timetagger__pb2.DeinitializeRequest.SerializeToString,
                response_deserializer=hal_dot_adapters_dot_timetagger_dot_v1_dot_timetagger__pb2.DeinitializeResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/hal.adapters.timetagger.v1.AdapterTimeTaggerService/GetStatus',
                request_serializer=hal_dot_adapters_dot_timetagger_dot_v1_dot_timetagger__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=hal_dot_adapters_dot_timetagger_dot_v1_dot_timetagger__pb2.GetStatusResponse.FromString,
                _registered_method=True)
        self.SetConfig = channel.unary_unary(
                '/hal.adapters.timetagger.v1.AdapterTimeTaggerService/SetConfig',
                request_serializer=hal_dot_adapters_dot_timetagger_dot_v1_dot_timetagger__pb2.SetConfigRequest.SerializeToString,
                response_deserializer=hal_dot_adapters_dot_timetagger_dot_v1_dot_timetagger__pb2.SetConfigResponse.FromString,
                _registered_method=True)
        self.AutoRecover = channel.unary_unary(
                '/hal.adapters.timetagger.v1.AdapterTimeTaggerService/AutoRecover',
                request_serializer=hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.AutoRecoverRequest.SerializeToString,
                response_deserializer=hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.AutoRecoverResponse.FromString,
                _registered_method=True)
        self.Tune = channel.unary_unary(
                '/hal.adapters.timetagger.v1.AdapterTimeTaggerService/Tune',
                request_serializer=hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.TuneRequest.SerializeToString,
                response_deserializer=hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.TuneResponse.FromString,
                _registered_method=True)
        self.StartDataCollection = channel.unary_unary(
                '/hal.adapters.timetagger.v1.AdapterTimeTaggerService/StartDataCollection',
                request_serializer=hal_dot_adapters_dot_timetagger_dot_v1_dot_timetagger__pb2.StartDataCollectionRequest.SerializeToString,
                response_deserializer=hal_dot_adapters_dot_timetagger_dot_v1_dot_timetagger__pb2.StartDataCollectionResponse.FromString,
                _registered_method=True)
        self.StopDataCollection = channel.unary_unary(
                '/hal.adapters.timetagger.v1.AdapterTimeTaggerService/StopDataCollection',
                request_serializer=hal_dot_adapters_dot_timetagger_dot_v1_dot_timetagger__pb2.StopDataCollectionRequest.SerializeToString,
                response_deserializer=hal_dot_adapters_dot_timetagger_dot_v1_dot_timetagger__pb2.StopDataCollectionResponse.FromString,
                _registered_method=True)
        self.TriggerEvent = channel.unary_unary(
                '/hal.adapters.timetagger.v1.AdapterTimeTaggerService/TriggerEvent',
                request_serializer=hal_dot_adapters_dot_timetagger_dot_v1_dot_timetagger__pb2.TriggerEventRequest.SerializeToString,
                response_deserializer=hal_dot_adapters_dot_timetagger_dot_v1_dot_timetagger__pb2.TriggerEventResponse.FromString,
                _registered_method=True)


class AdapterTimeTaggerServiceServicer:
    """--- Liveness & discovery ---
    """

    def HealthCheck(self, request, context):
        """Liveness of the adapter process itself. See common.proto.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResourceHealthCheck(self, request, context):
        """Health of the physical time-tagger hardware behind the adapter. See
        common.proto; the UP / DOWN / DEGRADED-style result may be informed by
        the device's current TimeTaggerState.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProductInfo(self, request, context):
        """Static identity of the hardware behind the adapter: serial number,
        vendor, firmware/software version.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Initialize(self, request, context):
        """--- Lifecycle ---

        Brings the time tagger from a freshly power-cycled state to
        ready-to-collect: connects to the device, loads calibration, and runs
        whatever bring-up sequence the hardware needs. Not every product needs
        preparation -- an adapter for hardware that's ready as soon as it's
        powered on may implement this as an immediate no-op that reports READY.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Deinitialize(self, request, context):
        """The opposite of Initialize: orderly shutdown once all jobs are done,
        releasing whatever Initialize acquired (e.g. closing the device
        connection). May also be a no-op where Initialize was.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """--- Status & configuration ---

        Current lifecycle state of the time tagger, plus which run (if any) it
        is bound to and its uptime. Poll this after Initialize/Deinitialize,
        and during data collection.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetConfig(self, request, context):
        """Updates the time tagger's operating configuration without a full
        Initialize/Deinitialize cycle.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AutoRecover(self, request, context):
        """--- Recovery ---

        Attempts the adapter's built-in automated recovery sequence to bring
        the time tagger back from TIME_TAGGER_STATE_DEGRADED (or FAULT) toward
        READY -- e.g. reconnecting to the device or re-loading calibration. See
        common.proto. Not every product needs a real recovery sequence -- an
        adapter may implement this as an immediate no-op, same as Initialize.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Tune(self, request, context):
        """Applies a single targeted adjustment as an alternative to a full
        AutoRecover sequence -- e.g. re-calibrate one channel rather than the
        whole device. See common.proto. Vendor-specific; adapters with no such
        fine-grained control may return UNIMPLEMENTED.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartDataCollection(self, request, context):
        """--- Data collection control ---

        Starts recording detector-click data for the given run. Called when the
        controller begins a job that needs timing/coincidence data (e.g. a
        heralding or QBER measurement). Requires TIME_TAGGER_STATE_READY; moves
        the time tagger into TIME_TAGGER_STATE_COLLECTING for the duration of
        the run. Vendor-specific measurement parameters (which channels,
        coincidence window, per-channel delays, where results are written,
        etc.) go in config_json.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopDataCollection(self, request, context):
        """Stops recording detector-click data for the given run and returns the
        time tagger to TIME_TAGGER_STATE_READY, available for the next run.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TriggerEvent(self, request, context):
        """--- Test / simulation hooks (optional) ---

        Triggers a special emulation/test condition for a running run -- e.g. a
        simulated eavesdropper, an induced fault, or an environmental
        perturbation. Not part of normal operation: an adapter with no such
        capability may return UNIMPLEMENTED.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdapterTimeTaggerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.HealthCheckRequest.FromString,
                    response_serializer=hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.HealthCheckResponse.SerializeToString,
            ),
            'ResourceHealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.ResourceHealthCheck,
                    request_deserializer=hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.ResourceHealthCheckRequest.FromString,
                    response_serializer=hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.ResourceHealthCheckResponse.SerializeToString,
            ),
            'GetProductInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProductInfo,
                    request_deserializer=hal_dot_adapters_dot_timetagger_dot_v1_dot_timetagger__pb2.GetProductInfoRequest.FromString,
                    response_serializer=hal_dot_adapters_dot_timetagger_dot_v1_dot_timetagger__pb2.GetProductInfoResponse.SerializeToString,
            ),
            'Initialize': grpc.unary_unary_rpc_method_handler(
                    servicer.Initialize,
                    request_deserializer=hal_dot_adapters_dot_timetagger_dot_v1_dot_timetagger__pb2.InitializeRequest.FromString,
                    response_serializer=hal_dot_adapters_dot_timetagger_dot_v1_dot_timetagger__pb2.InitializeResponse.SerializeToString,
            ),
            'Deinitialize': grpc.unary_unary_rpc_method_handler(
                    servicer.Deinitialize,
                    request_deserializer=hal_dot_adapters_dot_timetagger_dot_v1_dot_timetagger__pb2.DeinitializeRequest.FromString,
                    response_serializer=hal_dot_adapters_dot_timetagger_dot_v1_dot_timetagger__pb2.DeinitializeResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=hal_dot_adapters_dot_timetagger_dot_v1_dot_timetagger__pb2.GetStatusRequest.FromString,
                    response_serializer=hal_dot_adapters_dot_timetagger_dot_v1_dot_timetagger__pb2.GetStatusResponse.SerializeToString,
            ),
            'SetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SetConfig,
                    request_deserializer=hal_dot_adapters_dot_timetagger_dot_v1_dot_timetagger__pb2.SetConfigRequest.FromString,
                    response_serializer=hal_dot_adapters_dot_timetagger_dot_v1_dot_timetagger__pb2.SetConfigResponse.SerializeToString,
            ),
            'AutoRecover': grpc.unary_unary_rpc_method_handler(
                    servicer.AutoRecover,
                    request_deserializer=hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.AutoRecoverRequest.FromString,
                    response_serializer=hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.AutoRecoverResponse.SerializeToString,
            ),
            'Tune': grpc.unary_unary_rpc_method_handler(
                    servicer.Tune,
                    request_deserializer=hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.TuneRequest.FromString,
                    response_serializer=hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.TuneResponse.SerializeToString,
            ),
            'StartDataCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.StartDataCollection,
                    request_deserializer=hal_dot_adapters_dot_timetagger_dot_v1_dot_timetagger__pb2.StartDataCollectionRequest.FromString,
                    response_serializer=hal_dot_adapters_dot_timetagger_dot_v1_dot_timetagger__pb2.StartDataCollectionResponse.SerializeToString,
            ),
            'StopDataCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.StopDataCollection,
                    request_deserializer=hal_dot_adapters_dot_timetagger_dot_v1_dot_timetagger__pb2.StopDataCollectionRequest.FromString,
                    response_serializer=hal_dot_adapters_dot_timetagger_dot_v1_dot_timetagger__pb2.StopDataCollectionResponse.SerializeToString,
            ),
            'TriggerEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.TriggerEvent,
                    request_deserializer=hal_dot_adapters_dot_timetagger_dot_v1_dot_timetagger__pb2.TriggerEventRequest.FromString,
                    response_serializer=hal_dot_adapters_dot_timetagger_dot_v1_dot_timetagger__pb2.TriggerEventResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hal.adapters.timetagger.v1.AdapterTimeTaggerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hal.adapters.timetagger.v1.AdapterTimeTaggerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AdapterTimeTaggerService:
    """--- Liveness & discovery ---
    """

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hal.adapters.timetagger.v1.AdapterTimeTaggerService/HealthCheck',
            hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.HealthCheckRequest.SerializeToString,
            hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResourceHealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hal.adapters.timetagger.v1.AdapterTimeTaggerService/ResourceHealthCheck',
            hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.ResourceHealthCheckRequest.SerializeToString,
            hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.ResourceHealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProductInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hal.adapters.timetagger.v1.AdapterTimeTaggerService/GetProductInfo',
            hal_dot_adapters_dot_timetagger_dot_v1_dot_timetagger__pb2.GetProductInfoRequest.SerializeToString,
            hal_dot_adapters_dot_timetagger_dot_v1_dot_timetagger__pb2.GetProductInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Initialize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hal.adapters.timetagger.v1.AdapterTimeTaggerService/Initialize',
            hal_dot_adapters_dot_timetagger_dot_v1_dot_timetagger__pb2.InitializeRequest.SerializeToString,
            hal_dot_adapters_dot_timetagger_dot_v1_dot_timetagger__pb2.InitializeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Deinitialize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hal.adapters.timetagger.v1.AdapterTimeTaggerService/Deinitialize',
            hal_dot_adapters_dot_timetagger_dot_v1_dot_timetagger__pb2.DeinitializeRequest.SerializeToString,
            hal_dot_adapters_dot_timetagger_dot_v1_dot_timetagger__pb2.DeinitializeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hal.adapters.timetagger.v1.AdapterTimeTaggerService/GetStatus',
            hal_dot_adapters_dot_timetagger_dot_v1_dot_timetagger__pb2.GetStatusRequest.SerializeToString,
            hal_dot_adapters_dot_timetagger_dot_v1_dot_timetagger__pb2.GetStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hal.adapters.timetagger.v1.AdapterTimeTaggerService/SetConfig',
            hal_dot_adapters_dot_timetagger_dot_v1_dot_timetagger__pb2.SetConfigRequest.SerializeToString,
            hal_dot_adapters_dot_timetagger_dot_v1_dot_timetagger__pb2.SetConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AutoRecover(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hal.adapters.timetagger.v1.AdapterTimeTaggerService/AutoRecover',
            hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.AutoRecoverRequest.SerializeToString,
            hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.AutoRecoverResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Tune(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hal.adapters.timetagger.v1.AdapterTimeTaggerService/Tune',
            hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.TuneRequest.SerializeToString,
            hal_dot_adapters_dot_common_dot_v1_dot_common__pb2.TuneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartDataCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hal.adapters.timetagger.v1.AdapterTimeTaggerService/StartDataCollection',
            hal_dot_adapters_dot_timetagger_dot_v1_dot_timetagger__pb2.StartDataCollectionRequest.SerializeToString,
            hal_dot_adapters_dot_timetagger_dot_v1_dot_timetagger__pb2.StartDataCollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopDataCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hal.adapters.timetagger.v1.AdapterTimeTaggerService/StopDataCollection',
            hal_dot_adapters_dot_timetagger_dot_v1_dot_timetagger__pb2.StopDataCollectionRequest.SerializeToString,
            hal_dot_adapters_dot_timetagger_dot_v1_dot_timetagger__pb2.StopDataCollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TriggerEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hal.adapters.timetagger.v1.AdapterTimeTaggerService/TriggerEvent',
            hal_dot_adapters_dot_timetagger_dot_v1_dot_timetagger__pb2.TriggerEventRequest.SerializeToString,
            hal_dot_adapters_dot_timetagger_dot_v1_dot_timetagger__pb2.TriggerEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
