// Copyright 2026 Cisco Systems, Inc. and its affiliates
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: hal/adapters/switch/v1/switch.proto

package switchv1

import (
	context "context"
	v1 "github.com/outshift-open/quantum-hal/sdk/go/hal/adapters/common/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdapterSwitchService_HealthCheck_FullMethodName         = "/hal.adapters.switch.v1.AdapterSwitchService/HealthCheck"
	AdapterSwitchService_ResourceHealthCheck_FullMethodName = "/hal.adapters.switch.v1.AdapterSwitchService/ResourceHealthCheck"
	AdapterSwitchService_GetProductInfo_FullMethodName      = "/hal.adapters.switch.v1.AdapterSwitchService/GetProductInfo"
	AdapterSwitchService_Initialize_FullMethodName          = "/hal.adapters.switch.v1.AdapterSwitchService/Initialize"
	AdapterSwitchService_Deinitialize_FullMethodName        = "/hal.adapters.switch.v1.AdapterSwitchService/Deinitialize"
	AdapterSwitchService_GetStatus_FullMethodName           = "/hal.adapters.switch.v1.AdapterSwitchService/GetStatus"
	AdapterSwitchService_SetConfig_FullMethodName           = "/hal.adapters.switch.v1.AdapterSwitchService/SetConfig"
	AdapterSwitchService_AutoRecover_FullMethodName         = "/hal.adapters.switch.v1.AdapterSwitchService/AutoRecover"
	AdapterSwitchService_Tune_FullMethodName                = "/hal.adapters.switch.v1.AdapterSwitchService/Tune"
	AdapterSwitchService_CommitConnection_FullMethodName    = "/hal.adapters.switch.v1.AdapterSwitchService/CommitConnection"
	AdapterSwitchService_ClearConnections_FullMethodName    = "/hal.adapters.switch.v1.AdapterSwitchService/ClearConnections"
	AdapterSwitchService_ExecuteCommand_FullMethodName      = "/hal.adapters.switch.v1.AdapterSwitchService/ExecuteCommand"
	AdapterSwitchService_TriggerEvent_FullMethodName        = "/hal.adapters.switch.v1.AdapterSwitchService/TriggerEvent"
)

// AdapterSwitchServiceClient is the client API for AdapterSwitchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdapterSwitchServiceClient interface {
	// Liveness of the adapter process itself. See common.proto.
	HealthCheck(ctx context.Context, in *v1.HealthCheckRequest, opts ...grpc.CallOption) (*v1.HealthCheckResponse, error)
	// Health of the physical switch hardware behind the adapter. See
	// common.proto; the UP / DOWN / DEGRADED-style result may be informed by
	// the device's current SwitchState.
	ResourceHealthCheck(ctx context.Context, in *v1.ResourceHealthCheckRequest, opts ...grpc.CallOption) (*v1.ResourceHealthCheckResponse, error)
	// Static identity of the hardware behind the adapter: serial number,
	// vendor, firmware/software version, and the switch matrix size(s) it
	// exposes.
	GetProductInfo(ctx context.Context, in *GetProductInfoRequest, opts ...grpc.CallOption) (*GetProductInfoResponse, error)
	// Brings the switch from a freshly power-cycled state to ready-to-route:
	// homes/calibrates the switch fabric (e.g. MEMS mirror homing, fiber
	// alignment) and runs whatever self-test the hardware needs. Unlike
	// source's Initialize, switch homing is a short operation -- this call is
	// expected to block until it completes rather than requiring a status
	// poll.
	Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*InitializeResponse, error)
	// The opposite of Initialize: orderly shutdown once the switch is no
	// longer needed -- parks the switch fabric and releases whatever
	// Initialize acquired.
	Deinitialize(ctx context.Context, in *DeinitializeRequest, opts ...grpc.CallOption) (*DeinitializeResponse, error)
	// Current lifecycle state of the switch, plus its uptime. Poll this after
	// Initialize/Deinitialize.
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	// Updates the switch's operating configuration without a full
	// Initialize/Deinitialize cycle.
	SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*SetConfigResponse, error)
	// Attempts the adapter's built-in automated recovery sequence to bring
	// the switch back from SWITCH_STATE_DEGRADED (or FAULT) toward READY --
	// e.g. re-homing the fabric or whatever vendor-specific remediation
	// applies. See common.proto. Like Initialize, this is expected to block
	// until it completes rather than requiring a status poll.
	AutoRecover(ctx context.Context, in *v1.AutoRecoverRequest, opts ...grpc.CallOption) (*v1.AutoRecoverResponse, error)
	// Applies a single targeted adjustment as an alternative to a full
	// AutoRecover sequence -- e.g. re-home one path rather than the whole
	// fabric. See common.proto. Vendor-specific; adapters with no such
	// fine-grained control may return UNIMPLEMENTED.
	Tune(ctx context.Context, in *v1.TuneRequest, opts ...grpc.CallOption) (*v1.TuneResponse, error)
	// Establishes (or replaces) a signal path from input_port to output_port.
	CommitConnection(ctx context.Context, in *CommitConnectionRequest, opts ...grpc.CallOption) (*CommitConnectionResponse, error)
	// Tears down the connections on the given ports, freeing them for reuse.
	ClearConnections(ctx context.Context, in *ClearConnectionsRequest, opts ...grpc.CallOption) (*ClearConnectionsResponse, error)
	// Vendor-specific passthrough for commands not covered by the RPCs above
	// (e.g. a diagnostic or provisioning command with no structured
	// equivalent here). Implementing this RPC is optional: an adapter with no
	// need for raw command passthrough may return UNIMPLEMENTED.
	ExecuteCommand(ctx context.Context, in *ExecuteCommandRequest, opts ...grpc.CallOption) (*ExecuteCommandResponse, error)
	// Triggers a special, adapter-defined action -- not limited to
	// fault/emulation scenarios (e.g. an induced fault or an environmental
	// perturbation for testing); anything else the device might need done
	// mid-job that doesn't fit the RPCs above. Optional: an adapter with no
	// such capability may return UNIMPLEMENTED.
	TriggerEvent(ctx context.Context, in *TriggerEventRequest, opts ...grpc.CallOption) (*TriggerEventResponse, error)
}

type adapterSwitchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdapterSwitchServiceClient(cc grpc.ClientConnInterface) AdapterSwitchServiceClient {
	return &adapterSwitchServiceClient{cc}
}

func (c *adapterSwitchServiceClient) HealthCheck(ctx context.Context, in *v1.HealthCheckRequest, opts ...grpc.CallOption) (*v1.HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.HealthCheckResponse)
	err := c.cc.Invoke(ctx, AdapterSwitchService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterSwitchServiceClient) ResourceHealthCheck(ctx context.Context, in *v1.ResourceHealthCheckRequest, opts ...grpc.CallOption) (*v1.ResourceHealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.ResourceHealthCheckResponse)
	err := c.cc.Invoke(ctx, AdapterSwitchService_ResourceHealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterSwitchServiceClient) GetProductInfo(ctx context.Context, in *GetProductInfoRequest, opts ...grpc.CallOption) (*GetProductInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductInfoResponse)
	err := c.cc.Invoke(ctx, AdapterSwitchService_GetProductInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterSwitchServiceClient) Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*InitializeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitializeResponse)
	err := c.cc.Invoke(ctx, AdapterSwitchService_Initialize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterSwitchServiceClient) Deinitialize(ctx context.Context, in *DeinitializeRequest, opts ...grpc.CallOption) (*DeinitializeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeinitializeResponse)
	err := c.cc.Invoke(ctx, AdapterSwitchService_Deinitialize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterSwitchServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, AdapterSwitchService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterSwitchServiceClient) SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*SetConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetConfigResponse)
	err := c.cc.Invoke(ctx, AdapterSwitchService_SetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterSwitchServiceClient) AutoRecover(ctx context.Context, in *v1.AutoRecoverRequest, opts ...grpc.CallOption) (*v1.AutoRecoverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.AutoRecoverResponse)
	err := c.cc.Invoke(ctx, AdapterSwitchService_AutoRecover_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterSwitchServiceClient) Tune(ctx context.Context, in *v1.TuneRequest, opts ...grpc.CallOption) (*v1.TuneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.TuneResponse)
	err := c.cc.Invoke(ctx, AdapterSwitchService_Tune_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterSwitchServiceClient) CommitConnection(ctx context.Context, in *CommitConnectionRequest, opts ...grpc.CallOption) (*CommitConnectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitConnectionResponse)
	err := c.cc.Invoke(ctx, AdapterSwitchService_CommitConnection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterSwitchServiceClient) ClearConnections(ctx context.Context, in *ClearConnectionsRequest, opts ...grpc.CallOption) (*ClearConnectionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearConnectionsResponse)
	err := c.cc.Invoke(ctx, AdapterSwitchService_ClearConnections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterSwitchServiceClient) ExecuteCommand(ctx context.Context, in *ExecuteCommandRequest, opts ...grpc.CallOption) (*ExecuteCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteCommandResponse)
	err := c.cc.Invoke(ctx, AdapterSwitchService_ExecuteCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterSwitchServiceClient) TriggerEvent(ctx context.Context, in *TriggerEventRequest, opts ...grpc.CallOption) (*TriggerEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerEventResponse)
	err := c.cc.Invoke(ctx, AdapterSwitchService_TriggerEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdapterSwitchServiceServer is the server API for AdapterSwitchService service.
// All implementations must embed UnimplementedAdapterSwitchServiceServer
// for forward compatibility.
type AdapterSwitchServiceServer interface {
	// Liveness of the adapter process itself. See common.proto.
	HealthCheck(context.Context, *v1.HealthCheckRequest) (*v1.HealthCheckResponse, error)
	// Health of the physical switch hardware behind the adapter. See
	// common.proto; the UP / DOWN / DEGRADED-style result may be informed by
	// the device's current SwitchState.
	ResourceHealthCheck(context.Context, *v1.ResourceHealthCheckRequest) (*v1.ResourceHealthCheckResponse, error)
	// Static identity of the hardware behind the adapter: serial number,
	// vendor, firmware/software version, and the switch matrix size(s) it
	// exposes.
	GetProductInfo(context.Context, *GetProductInfoRequest) (*GetProductInfoResponse, error)
	// Brings the switch from a freshly power-cycled state to ready-to-route:
	// homes/calibrates the switch fabric (e.g. MEMS mirror homing, fiber
	// alignment) and runs whatever self-test the hardware needs. Unlike
	// source's Initialize, switch homing is a short operation -- this call is
	// expected to block until it completes rather than requiring a status
	// poll.
	Initialize(context.Context, *InitializeRequest) (*InitializeResponse, error)
	// The opposite of Initialize: orderly shutdown once the switch is no
	// longer needed -- parks the switch fabric and releases whatever
	// Initialize acquired.
	Deinitialize(context.Context, *DeinitializeRequest) (*DeinitializeResponse, error)
	// Current lifecycle state of the switch, plus its uptime. Poll this after
	// Initialize/Deinitialize.
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	// Updates the switch's operating configuration without a full
	// Initialize/Deinitialize cycle.
	SetConfig(context.Context, *SetConfigRequest) (*SetConfigResponse, error)
	// Attempts the adapter's built-in automated recovery sequence to bring
	// the switch back from SWITCH_STATE_DEGRADED (or FAULT) toward READY --
	// e.g. re-homing the fabric or whatever vendor-specific remediation
	// applies. See common.proto. Like Initialize, this is expected to block
	// until it completes rather than requiring a status poll.
	AutoRecover(context.Context, *v1.AutoRecoverRequest) (*v1.AutoRecoverResponse, error)
	// Applies a single targeted adjustment as an alternative to a full
	// AutoRecover sequence -- e.g. re-home one path rather than the whole
	// fabric. See common.proto. Vendor-specific; adapters with no such
	// fine-grained control may return UNIMPLEMENTED.
	Tune(context.Context, *v1.TuneRequest) (*v1.TuneResponse, error)
	// Establishes (or replaces) a signal path from input_port to output_port.
	CommitConnection(context.Context, *CommitConnectionRequest) (*CommitConnectionResponse, error)
	// Tears down the connections on the given ports, freeing them for reuse.
	ClearConnections(context.Context, *ClearConnectionsRequest) (*ClearConnectionsResponse, error)
	// Vendor-specific passthrough for commands not covered by the RPCs above
	// (e.g. a diagnostic or provisioning command with no structured
	// equivalent here). Implementing this RPC is optional: an adapter with no
	// need for raw command passthrough may return UNIMPLEMENTED.
	ExecuteCommand(context.Context, *ExecuteCommandRequest) (*ExecuteCommandResponse, error)
	// Triggers a special, adapter-defined action -- not limited to
	// fault/emulation scenarios (e.g. an induced fault or an environmental
	// perturbation for testing); anything else the device might need done
	// mid-job that doesn't fit the RPCs above. Optional: an adapter with no
	// such capability may return UNIMPLEMENTED.
	TriggerEvent(context.Context, *TriggerEventRequest) (*TriggerEventResponse, error)
	mustEmbedUnimplementedAdapterSwitchServiceServer()
}

// UnimplementedAdapterSwitchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdapterSwitchServiceServer struct{}

func (UnimplementedAdapterSwitchServiceServer) HealthCheck(context.Context, *v1.HealthCheckRequest) (*v1.HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedAdapterSwitchServiceServer) ResourceHealthCheck(context.Context, *v1.ResourceHealthCheckRequest) (*v1.ResourceHealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResourceHealthCheck not implemented")
}
func (UnimplementedAdapterSwitchServiceServer) GetProductInfo(context.Context, *GetProductInfoRequest) (*GetProductInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProductInfo not implemented")
}
func (UnimplementedAdapterSwitchServiceServer) Initialize(context.Context, *InitializeRequest) (*InitializeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Initialize not implemented")
}
func (UnimplementedAdapterSwitchServiceServer) Deinitialize(context.Context, *DeinitializeRequest) (*DeinitializeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Deinitialize not implemented")
}
func (UnimplementedAdapterSwitchServiceServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedAdapterSwitchServiceServer) SetConfig(context.Context, *SetConfigRequest) (*SetConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetConfig not implemented")
}
func (UnimplementedAdapterSwitchServiceServer) AutoRecover(context.Context, *v1.AutoRecoverRequest) (*v1.AutoRecoverResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AutoRecover not implemented")
}
func (UnimplementedAdapterSwitchServiceServer) Tune(context.Context, *v1.TuneRequest) (*v1.TuneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Tune not implemented")
}
func (UnimplementedAdapterSwitchServiceServer) CommitConnection(context.Context, *CommitConnectionRequest) (*CommitConnectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitConnection not implemented")
}
func (UnimplementedAdapterSwitchServiceServer) ClearConnections(context.Context, *ClearConnectionsRequest) (*ClearConnectionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClearConnections not implemented")
}
func (UnimplementedAdapterSwitchServiceServer) ExecuteCommand(context.Context, *ExecuteCommandRequest) (*ExecuteCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteCommand not implemented")
}
func (UnimplementedAdapterSwitchServiceServer) TriggerEvent(context.Context, *TriggerEventRequest) (*TriggerEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerEvent not implemented")
}
func (UnimplementedAdapterSwitchServiceServer) mustEmbedUnimplementedAdapterSwitchServiceServer() {}
func (UnimplementedAdapterSwitchServiceServer) testEmbeddedByValue()                              {}

// UnsafeAdapterSwitchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdapterSwitchServiceServer will
// result in compilation errors.
type UnsafeAdapterSwitchServiceServer interface {
	mustEmbedUnimplementedAdapterSwitchServiceServer()
}

func RegisterAdapterSwitchServiceServer(s grpc.ServiceRegistrar, srv AdapterSwitchServiceServer) {
	// If the following call panics, it indicates UnimplementedAdapterSwitchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdapterSwitchService_ServiceDesc, srv)
}

func _AdapterSwitchService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterSwitchServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterSwitchService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterSwitchServiceServer).HealthCheck(ctx, req.(*v1.HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterSwitchService_ResourceHealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.ResourceHealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterSwitchServiceServer).ResourceHealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterSwitchService_ResourceHealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterSwitchServiceServer).ResourceHealthCheck(ctx, req.(*v1.ResourceHealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterSwitchService_GetProductInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterSwitchServiceServer).GetProductInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterSwitchService_GetProductInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterSwitchServiceServer).GetProductInfo(ctx, req.(*GetProductInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterSwitchService_Initialize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitializeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterSwitchServiceServer).Initialize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterSwitchService_Initialize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterSwitchServiceServer).Initialize(ctx, req.(*InitializeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterSwitchService_Deinitialize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeinitializeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterSwitchServiceServer).Deinitialize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterSwitchService_Deinitialize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterSwitchServiceServer).Deinitialize(ctx, req.(*DeinitializeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterSwitchService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterSwitchServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterSwitchService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterSwitchServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterSwitchService_SetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterSwitchServiceServer).SetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterSwitchService_SetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterSwitchServiceServer).SetConfig(ctx, req.(*SetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterSwitchService_AutoRecover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.AutoRecoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterSwitchServiceServer).AutoRecover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterSwitchService_AutoRecover_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterSwitchServiceServer).AutoRecover(ctx, req.(*v1.AutoRecoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterSwitchService_Tune_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.TuneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterSwitchServiceServer).Tune(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterSwitchService_Tune_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterSwitchServiceServer).Tune(ctx, req.(*v1.TuneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterSwitchService_CommitConnection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitConnectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterSwitchServiceServer).CommitConnection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterSwitchService_CommitConnection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterSwitchServiceServer).CommitConnection(ctx, req.(*CommitConnectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterSwitchService_ClearConnections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearConnectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterSwitchServiceServer).ClearConnections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterSwitchService_ClearConnections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterSwitchServiceServer).ClearConnections(ctx, req.(*ClearConnectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterSwitchService_ExecuteCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterSwitchServiceServer).ExecuteCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterSwitchService_ExecuteCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterSwitchServiceServer).ExecuteCommand(ctx, req.(*ExecuteCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterSwitchService_TriggerEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterSwitchServiceServer).TriggerEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterSwitchService_TriggerEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterSwitchServiceServer).TriggerEvent(ctx, req.(*TriggerEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdapterSwitchService_ServiceDesc is the grpc.ServiceDesc for AdapterSwitchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdapterSwitchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hal.adapters.switch.v1.AdapterSwitchService",
	HandlerType: (*AdapterSwitchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _AdapterSwitchService_HealthCheck_Handler,
		},
		{
			MethodName: "ResourceHealthCheck",
			Handler:    _AdapterSwitchService_ResourceHealthCheck_Handler,
		},
		{
			MethodName: "GetProductInfo",
			Handler:    _AdapterSwitchService_GetProductInfo_Handler,
		},
		{
			MethodName: "Initialize",
			Handler:    _AdapterSwitchService_Initialize_Handler,
		},
		{
			MethodName: "Deinitialize",
			Handler:    _AdapterSwitchService_Deinitialize_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _AdapterSwitchService_GetStatus_Handler,
		},
		{
			MethodName: "SetConfig",
			Handler:    _AdapterSwitchService_SetConfig_Handler,
		},
		{
			MethodName: "AutoRecover",
			Handler:    _AdapterSwitchService_AutoRecover_Handler,
		},
		{
			MethodName: "Tune",
			Handler:    _AdapterSwitchService_Tune_Handler,
		},
		{
			MethodName: "CommitConnection",
			Handler:    _AdapterSwitchService_CommitConnection_Handler,
		},
		{
			MethodName: "ClearConnections",
			Handler:    _AdapterSwitchService_ClearConnections_Handler,
		},
		{
			MethodName: "ExecuteCommand",
			Handler:    _AdapterSwitchService_ExecuteCommand_Handler,
		},
		{
			MethodName: "TriggerEvent",
			Handler:    _AdapterSwitchService_TriggerEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hal/adapters/switch/v1/switch.proto",
}
