// Copyright 2026 Cisco Systems, Inc. and its affiliates
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: hal/adapters/switch/v1/switch.proto

package switchv1

import (
	v1 "github.com/outshift-open/quantum-hal/sdk/go/hal/adapters/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Lifecycle of the switch hardware.
type SwitchState int32

const (
	SwitchState_SWITCH_STATE_UNSPECIFIED SwitchState = 0
	// Powered, not yet homed/calibrated -- the OFF of the state machine.
	SwitchState_SWITCH_STATE_IDLE SwitchState = 1
	// Homing/calibrating the switch fabric and running self-test.
	SwitchState_SWITCH_STATE_INITIALIZING SwitchState = 2
	// Homed and calibrated; accepts CommitConnection/ClearConnections.
	SwitchState_SWITCH_STATE_READY          SwitchState = 3
	SwitchState_SWITCH_STATE_FAULT          SwitchState = 4
	SwitchState_SWITCH_STATE_DEINITIALIZING SwitchState = 5
	// Operational, but the hardware reports degraded performance on at least
	// one path (e.g. elevated insertion loss, a flaky port).
	SwitchState_SWITCH_STATE_DEGRADED SwitchState = 6
)

// Enum value maps for SwitchState.
var (
	SwitchState_name = map[int32]string{
		0: "SWITCH_STATE_UNSPECIFIED",
		1: "SWITCH_STATE_IDLE",
		2: "SWITCH_STATE_INITIALIZING",
		3: "SWITCH_STATE_READY",
		4: "SWITCH_STATE_FAULT",
		5: "SWITCH_STATE_DEINITIALIZING",
		6: "SWITCH_STATE_DEGRADED",
	}
	SwitchState_value = map[string]int32{
		"SWITCH_STATE_UNSPECIFIED":    0,
		"SWITCH_STATE_IDLE":           1,
		"SWITCH_STATE_INITIALIZING":   2,
		"SWITCH_STATE_READY":          3,
		"SWITCH_STATE_FAULT":          4,
		"SWITCH_STATE_DEINITIALIZING": 5,
		"SWITCH_STATE_DEGRADED":       6,
	}
)

func (x SwitchState) Enum() *SwitchState {
	p := new(SwitchState)
	*p = x
	return p
}

func (x SwitchState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SwitchState) Descriptor() protoreflect.EnumDescriptor {
	return file_hal_adapters_switch_v1_switch_proto_enumTypes[0].Descriptor()
}

func (SwitchState) Type() protoreflect.EnumType {
	return &file_hal_adapters_switch_v1_switch_proto_enumTypes[0]
}

func (x SwitchState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SwitchState.Descriptor instead.
func (SwitchState) EnumDescriptor() ([]byte, []int) {
	return file_hal_adapters_switch_v1_switch_proto_rawDescGZIP(), []int{0}
}

type GetProductInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ResourceType  string                 `protobuf:"bytes,2,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductInfoRequest) Reset() {
	*x = GetProductInfoRequest{}
	mi := &file_hal_adapters_switch_v1_switch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductInfoRequest) ProtoMessage() {}

func (x *GetProductInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_switch_v1_switch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductInfoRequest.ProtoReflect.Descriptor instead.
func (*GetProductInfoRequest) Descriptor() ([]byte, []int) {
	return file_hal_adapters_switch_v1_switch_proto_rawDescGZIP(), []int{0}
}

func (x *GetProductInfoRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *GetProductInfoRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

type GetProductInfoResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SerialNumber    string                 `protobuf:"bytes,1,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	ProductCode     string                 `protobuf:"bytes,2,opt,name=product_code,json=productCode,proto3" json:"product_code,omitempty"`
	SoftwareVersion string                 `protobuf:"bytes,3,opt,name=software_version,json=softwareVersion,proto3" json:"software_version,omitempty"`
	Vendor          string                 `protobuf:"bytes,4,opt,name=vendor,proto3" json:"vendor,omitempty"`
	// Sizes of the switch matrix/matrices this product exposes (e.g. an 8x8
	// fabric reports 8).
	SwitchSizes   []int64 `protobuf:"varint,5,rep,packed,name=switch_sizes,json=switchSizes,proto3" json:"switch_sizes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductInfoResponse) Reset() {
	*x = GetProductInfoResponse{}
	mi := &file_hal_adapters_switch_v1_switch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductInfoResponse) ProtoMessage() {}

func (x *GetProductInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_switch_v1_switch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductInfoResponse.ProtoReflect.Descriptor instead.
func (*GetProductInfoResponse) Descriptor() ([]byte, []int) {
	return file_hal_adapters_switch_v1_switch_proto_rawDescGZIP(), []int{1}
}

func (x *GetProductInfoResponse) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *GetProductInfoResponse) GetProductCode() string {
	if x != nil {
		return x.ProductCode
	}
	return ""
}

func (x *GetProductInfoResponse) GetSoftwareVersion() string {
	if x != nil {
		return x.SoftwareVersion
	}
	return ""
}

func (x *GetProductInfoResponse) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

func (x *GetProductInfoResponse) GetSwitchSizes() []int64 {
	if x != nil {
		return x.SwitchSizes
	}
	return nil
}

// Vendor-specific bring-up parameters, if a given product needs any (e.g.
// calibration targets, a default routing table). Encoded as a JSON object;
// each product's adapter implementation defines and documents its own
// schema and is responsible for parsing it. Leave empty if the product
// needs no configuration to home/calibrate.
type InitializeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ConfigJson    string                 `protobuf:"bytes,2,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	ResourceType  string                 `protobuf:"bytes,3,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeRequest) Reset() {
	*x = InitializeRequest{}
	mi := &file_hal_adapters_switch_v1_switch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeRequest) ProtoMessage() {}

func (x *InitializeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_switch_v1_switch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeRequest.ProtoReflect.Descriptor instead.
func (*InitializeRequest) Descriptor() ([]byte, []int) {
	return file_hal_adapters_switch_v1_switch_proto_rawDescGZIP(), []int{2}
}

func (x *InitializeRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *InitializeRequest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

func (x *InitializeRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

type InitializeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeResponse) Reset() {
	*x = InitializeResponse{}
	mi := &file_hal_adapters_switch_v1_switch_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeResponse) ProtoMessage() {}

func (x *InitializeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_switch_v1_switch_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeResponse.ProtoReflect.Descriptor instead.
func (*InitializeResponse) Descriptor() ([]byte, []int) {
	return file_hal_adapters_switch_v1_switch_proto_rawDescGZIP(), []int{3}
}

func (x *InitializeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeinitializeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ResourceType  string                 `protobuf:"bytes,2,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeinitializeRequest) Reset() {
	*x = DeinitializeRequest{}
	mi := &file_hal_adapters_switch_v1_switch_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeinitializeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeinitializeRequest) ProtoMessage() {}

func (x *DeinitializeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_switch_v1_switch_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeinitializeRequest.ProtoReflect.Descriptor instead.
func (*DeinitializeRequest) Descriptor() ([]byte, []int) {
	return file_hal_adapters_switch_v1_switch_proto_rawDescGZIP(), []int{4}
}

func (x *DeinitializeRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *DeinitializeRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

type DeinitializeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeinitializeResponse) Reset() {
	*x = DeinitializeResponse{}
	mi := &file_hal_adapters_switch_v1_switch_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeinitializeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeinitializeResponse) ProtoMessage() {}

func (x *DeinitializeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_switch_v1_switch_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeinitializeResponse.ProtoReflect.Descriptor instead.
func (*DeinitializeResponse) Descriptor() ([]byte, []int) {
	return file_hal_adapters_switch_v1_switch_proto_rawDescGZIP(), []int{5}
}

func (x *DeinitializeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ResourceType  string                 `protobuf:"bytes,2,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_hal_adapters_switch_v1_switch_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_switch_v1_switch_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_hal_adapters_switch_v1_switch_proto_rawDescGZIP(), []int{6}
}

func (x *GetStatusRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *GetStatusRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         SwitchState            `protobuf:"varint,1,opt,name=state,proto3,enum=hal.adapters.switch.v1.SwitchState" json:"state,omitempty"`
	UptimeSeconds float32                `protobuf:"fixed32,2,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	// Vendor-specific status detail beyond the common SwitchState (e.g.
	// per-port link status, temperature, fan speed). Encoded as a JSON
	// object; each product's adapter implementation defines and documents its
	// own schema for it.
	StatusJson    string `protobuf:"bytes,3,opt,name=status_json,json=statusJson,proto3" json:"status_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_hal_adapters_switch_v1_switch_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_switch_v1_switch_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_hal_adapters_switch_v1_switch_proto_rawDescGZIP(), []int{7}
}

func (x *GetStatusResponse) GetState() SwitchState {
	if x != nil {
		return x.State
	}
	return SwitchState_SWITCH_STATE_UNSPECIFIED
}

func (x *GetStatusResponse) GetUptimeSeconds() float32 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *GetStatusResponse) GetStatusJson() string {
	if x != nil {
		return x.StatusJson
	}
	return ""
}

type SetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ConfigJson    string                 `protobuf:"bytes,2,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	ResourceType  string                 `protobuf:"bytes,3,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConfigRequest) Reset() {
	*x = SetConfigRequest{}
	mi := &file_hal_adapters_switch_v1_switch_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConfigRequest) ProtoMessage() {}

func (x *SetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_switch_v1_switch_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConfigRequest.ProtoReflect.Descriptor instead.
func (*SetConfigRequest) Descriptor() ([]byte, []int) {
	return file_hal_adapters_switch_v1_switch_proto_rawDescGZIP(), []int{8}
}

func (x *SetConfigRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *SetConfigRequest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

func (x *SetConfigRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

type SetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConfigResponse) Reset() {
	*x = SetConfigResponse{}
	mi := &file_hal_adapters_switch_v1_switch_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConfigResponse) ProtoMessage() {}

func (x *SetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_switch_v1_switch_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConfigResponse.ProtoReflect.Descriptor instead.
func (*SetConfigResponse) Descriptor() ([]byte, []int) {
	return file_hal_adapters_switch_v1_switch_proto_rawDescGZIP(), []int{9}
}

func (x *SetConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CommitConnectionRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	ProductId  string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	InputPort  int64                  `protobuf:"varint,2,opt,name=input_port,json=inputPort,proto3" json:"input_port,omitempty"`
	OutputPort int64                  `protobuf:"varint,3,opt,name=output_port,json=outputPort,proto3" json:"output_port,omitempty"`
	// Physical routing mode for this connection, for fabrics that support
	// more than one: "bar" passes the signal straight through (the classic
	// 2x2-switch bar state, input N to output N on the same side of the
	// fabric); "cross" routes it to the other output instead. Vendor-defined
	// encoding; adapters for hardware with only one routing mode may ignore
	// this field. 0 means "not applicable / use whatever the hardware
	// supports."
	RoutingCase   int32  `protobuf:"varint,4,opt,name=routing_case,json=routingCase,proto3" json:"routing_case,omitempty"`
	ResourceType  string `protobuf:"bytes,5,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitConnectionRequest) Reset() {
	*x = CommitConnectionRequest{}
	mi := &file_hal_adapters_switch_v1_switch_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitConnectionRequest) ProtoMessage() {}

func (x *CommitConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_switch_v1_switch_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitConnectionRequest.ProtoReflect.Descriptor instead.
func (*CommitConnectionRequest) Descriptor() ([]byte, []int) {
	return file_hal_adapters_switch_v1_switch_proto_rawDescGZIP(), []int{10}
}

func (x *CommitConnectionRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *CommitConnectionRequest) GetInputPort() int64 {
	if x != nil {
		return x.InputPort
	}
	return 0
}

func (x *CommitConnectionRequest) GetOutputPort() int64 {
	if x != nil {
		return x.OutputPort
	}
	return 0
}

func (x *CommitConnectionRequest) GetRoutingCase() int32 {
	if x != nil {
		return x.RoutingCase
	}
	return 0
}

func (x *CommitConnectionRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

type CommitConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitConnectionResponse) Reset() {
	*x = CommitConnectionResponse{}
	mi := &file_hal_adapters_switch_v1_switch_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitConnectionResponse) ProtoMessage() {}

func (x *CommitConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_switch_v1_switch_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitConnectionResponse.ProtoReflect.Descriptor instead.
func (*CommitConnectionResponse) Descriptor() ([]byte, []int) {
	return file_hal_adapters_switch_v1_switch_proto_rawDescGZIP(), []int{11}
}

func (x *CommitConnectionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ClearConnectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Ports         []int64                `protobuf:"varint,2,rep,packed,name=ports,proto3" json:"ports,omitempty"`
	ResourceType  string                 `protobuf:"bytes,3,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearConnectionsRequest) Reset() {
	*x = ClearConnectionsRequest{}
	mi := &file_hal_adapters_switch_v1_switch_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearConnectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearConnectionsRequest) ProtoMessage() {}

func (x *ClearConnectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_switch_v1_switch_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearConnectionsRequest.ProtoReflect.Descriptor instead.
func (*ClearConnectionsRequest) Descriptor() ([]byte, []int) {
	return file_hal_adapters_switch_v1_switch_proto_rawDescGZIP(), []int{12}
}

func (x *ClearConnectionsRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ClearConnectionsRequest) GetPorts() []int64 {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *ClearConnectionsRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

type ClearConnectionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearConnectionsResponse) Reset() {
	*x = ClearConnectionsResponse{}
	mi := &file_hal_adapters_switch_v1_switch_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearConnectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearConnectionsResponse) ProtoMessage() {}

func (x *ClearConnectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_switch_v1_switch_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearConnectionsResponse.ProtoReflect.Descriptor instead.
func (*ClearConnectionsResponse) Descriptor() ([]byte, []int) {
	return file_hal_adapters_switch_v1_switch_proto_rawDescGZIP(), []int{13}
}

func (x *ClearConnectionsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Vendor-specific raw command, encoded as a JSON object. This spec doesn't
// model connection transport (tcp/serial), addressing, or payload shape --
// each product's adapter implementation defines and documents its own
// schema for command_json and is responsible for parsing it.
type ExecuteCommandRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	CommandJson   string                 `protobuf:"bytes,2,opt,name=command_json,json=commandJson,proto3" json:"command_json,omitempty"`
	ResourceType  string                 `protobuf:"bytes,3,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteCommandRequest) Reset() {
	*x = ExecuteCommandRequest{}
	mi := &file_hal_adapters_switch_v1_switch_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteCommandRequest) ProtoMessage() {}

func (x *ExecuteCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_switch_v1_switch_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteCommandRequest.ProtoReflect.Descriptor instead.
func (*ExecuteCommandRequest) Descriptor() ([]byte, []int) {
	return file_hal_adapters_switch_v1_switch_proto_rawDescGZIP(), []int{14}
}

func (x *ExecuteCommandRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ExecuteCommandRequest) GetCommandJson() string {
	if x != nil {
		return x.CommandJson
	}
	return ""
}

func (x *ExecuteCommandRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

type ExecuteCommandResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Vendor-specific result, per whatever schema the adapter implementation
	// defined for command_json.
	ResponseJson  string `protobuf:"bytes,1,opt,name=response_json,json=responseJson,proto3" json:"response_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteCommandResponse) Reset() {
	*x = ExecuteCommandResponse{}
	mi := &file_hal_adapters_switch_v1_switch_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteCommandResponse) ProtoMessage() {}

func (x *ExecuteCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_switch_v1_switch_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteCommandResponse.ProtoReflect.Descriptor instead.
func (*ExecuteCommandResponse) Descriptor() ([]byte, []int) {
	return file_hal_adapters_switch_v1_switch_proto_rawDescGZIP(), []int{15}
}

func (x *ExecuteCommandResponse) GetResponseJson() string {
	if x != nil {
		return x.ResponseJson
	}
	return ""
}

// event_type names which action to trigger (e.g. "fault", "perturbation",
// or anything else a product needs mid-job) -- adapter- and
// product-defined, not enumerated here. payload_json carries whatever
// parameters that action needs, encoded as a JSON object, per a schema the
// adapter implementation defines and documents for that event_type.
type TriggerEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,4,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	ResourceType  string                 `protobuf:"bytes,5,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerEventRequest) Reset() {
	*x = TriggerEventRequest{}
	mi := &file_hal_adapters_switch_v1_switch_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerEventRequest) ProtoMessage() {}

func (x *TriggerEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_switch_v1_switch_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerEventRequest.ProtoReflect.Descriptor instead.
func (*TriggerEventRequest) Descriptor() ([]byte, []int) {
	return file_hal_adapters_switch_v1_switch_proto_rawDescGZIP(), []int{16}
}

func (x *TriggerEventRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *TriggerEventRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *TriggerEventRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *TriggerEventRequest) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

func (x *TriggerEventRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

type TriggerEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerEventResponse) Reset() {
	*x = TriggerEventResponse{}
	mi := &file_hal_adapters_switch_v1_switch_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerEventResponse) ProtoMessage() {}

func (x *TriggerEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_switch_v1_switch_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerEventResponse.ProtoReflect.Descriptor instead.
func (*TriggerEventResponse) Descriptor() ([]byte, []int) {
	return file_hal_adapters_switch_v1_switch_proto_rawDescGZIP(), []int{17}
}

func (x *TriggerEventResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_hal_adapters_switch_v1_switch_proto protoreflect.FileDescriptor

const file_hal_adapters_switch_v1_switch_proto_rawDesc = "" +
	"\n" +
	"#hal/adapters/switch/v1/switch.proto\x12\x16hal.adapters.switch.v1\x1a#hal/adapters/common/v1/common.proto\"[\n" +
	"\x15GetProductInfoRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12#\n" +
	"\rresource_type\x18\x02 \x01(\tR\fresourceType\"\xc6\x01\n" +
	"\x16GetProductInfoResponse\x12#\n" +
	"\rserial_number\x18\x01 \x01(\tR\fserialNumber\x12!\n" +
	"\fproduct_code\x18\x02 \x01(\tR\vproductCode\x12)\n" +
	"\x10software_version\x18\x03 \x01(\tR\x0fsoftwareVersion\x12\x16\n" +
	"\x06vendor\x18\x04 \x01(\tR\x06vendor\x12!\n" +
	"\fswitch_sizes\x18\x05 \x03(\x03R\vswitchSizes\"x\n" +
	"\x11InitializeRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1f\n" +
	"\vconfig_json\x18\x02 \x01(\tR\n" +
	"configJson\x12#\n" +
	"\rresource_type\x18\x03 \x01(\tR\fresourceType\".\n" +
	"\x12InitializeResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"Y\n" +
	"\x13DeinitializeRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12#\n" +
	"\rresource_type\x18\x02 \x01(\tR\fresourceType\"0\n" +
	"\x14DeinitializeResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"V\n" +
	"\x10GetStatusRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12#\n" +
	"\rresource_type\x18\x02 \x01(\tR\fresourceType\"\x96\x01\n" +
	"\x11GetStatusResponse\x129\n" +
	"\x05state\x18\x01 \x01(\x0e2#.hal.adapters.switch.v1.SwitchStateR\x05state\x12%\n" +
	"\x0euptime_seconds\x18\x02 \x01(\x02R\ruptimeSeconds\x12\x1f\n" +
	"\vstatus_json\x18\x03 \x01(\tR\n" +
	"statusJson\"w\n" +
	"\x10SetConfigRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1f\n" +
	"\vconfig_json\x18\x02 \x01(\tR\n" +
	"configJson\x12#\n" +
	"\rresource_type\x18\x03 \x01(\tR\fresourceType\"-\n" +
	"\x11SetConfigResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xc0\x01\n" +
	"\x17CommitConnectionRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1d\n" +
	"\n" +
	"input_port\x18\x02 \x01(\x03R\tinputPort\x12\x1f\n" +
	"\voutput_port\x18\x03 \x01(\x03R\n" +
	"outputPort\x12!\n" +
	"\frouting_case\x18\x04 \x01(\x05R\vroutingCase\x12#\n" +
	"\rresource_type\x18\x05 \x01(\tR\fresourceType\"4\n" +
	"\x18CommitConnectionResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"s\n" +
	"\x17ClearConnectionsRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x14\n" +
	"\x05ports\x18\x02 \x03(\x03R\x05ports\x12#\n" +
	"\rresource_type\x18\x03 \x01(\tR\fresourceType\"4\n" +
	"\x18ClearConnectionsResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"~\n" +
	"\x15ExecuteCommandRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12!\n" +
	"\fcommand_json\x18\x02 \x01(\tR\vcommandJson\x12#\n" +
	"\rresource_type\x18\x03 \x01(\tR\fresourceType\"=\n" +
	"\x16ExecuteCommandResponse\x12#\n" +
	"\rresponse_json\x18\x01 \x01(\tR\fresponseJson\"\xb2\x01\n" +
	"\x13TriggerEventRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12!\n" +
	"\fpayload_json\x18\x04 \x01(\tR\vpayloadJson\x12#\n" +
	"\rresource_type\x18\x05 \x01(\tR\fresourceType\"0\n" +
	"\x14TriggerEventResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage*\xcd\x01\n" +
	"\vSwitchState\x12\x1c\n" +
	"\x18SWITCH_STATE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11SWITCH_STATE_IDLE\x10\x01\x12\x1d\n" +
	"\x19SWITCH_STATE_INITIALIZING\x10\x02\x12\x16\n" +
	"\x12SWITCH_STATE_READY\x10\x03\x12\x16\n" +
	"\x12SWITCH_STATE_FAULT\x10\x04\x12\x1f\n" +
	"\x1bSWITCH_STATE_DEINITIALIZING\x10\x05\x12\x19\n" +
	"\x15SWITCH_STATE_DEGRADED\x10\x062\x88\v\n" +
	"\x14AdapterSwitchService\x12f\n" +
	"\vHealthCheck\x12*.hal.adapters.common.v1.HealthCheckRequest\x1a+.hal.adapters.common.v1.HealthCheckResponse\x12~\n" +
	"\x13ResourceHealthCheck\x122.hal.adapters.common.v1.ResourceHealthCheckRequest\x1a3.hal.adapters.common.v1.ResourceHealthCheckResponse\x12o\n" +
	"\x0eGetProductInfo\x12-.hal.adapters.switch.v1.GetProductInfoRequest\x1a..hal.adapters.switch.v1.GetProductInfoResponse\x12c\n" +
	"\n" +
	"Initialize\x12).hal.adapters.switch.v1.InitializeRequest\x1a*.hal.adapters.switch.v1.InitializeResponse\x12i\n" +
	"\fDeinitialize\x12+.hal.adapters.switch.v1.DeinitializeRequest\x1a,.hal.adapters.switch.v1.DeinitializeResponse\x12`\n" +
	"\tGetStatus\x12(.hal.adapters.switch.v1.GetStatusRequest\x1a).hal.adapters.switch.v1.GetStatusResponse\x12`\n" +
	"\tSetConfig\x12(.hal.adapters.switch.v1.SetConfigRequest\x1a).hal.adapters.switch.v1.SetConfigResponse\x12f\n" +
	"\vAutoRecover\x12*.hal.adapters.common.v1.AutoRecoverRequest\x1a+.hal.adapters.common.v1.AutoRecoverResponse\x12Q\n" +
	"\x04Tune\x12#.hal.adapters.common.v1.TuneRequest\x1a$.hal.adapters.common.v1.TuneResponse\x12u\n" +
	"\x10CommitConnection\x12/.hal.adapters.switch.v1.CommitConnectionRequest\x1a0.hal.adapters.switch.v1.CommitConnectionResponse\x12u\n" +
	"\x10ClearConnections\x12/.hal.adapters.switch.v1.ClearConnectionsRequest\x1a0.hal.adapters.switch.v1.ClearConnectionsResponse\x12o\n" +
	"\x0eExecuteCommand\x12-.hal.adapters.switch.v1.ExecuteCommandRequest\x1a..hal.adapters.switch.v1.ExecuteCommandResponse\x12i\n" +
	"\fTriggerEvent\x12+.hal.adapters.switch.v1.TriggerEventRequest\x1a,.hal.adapters.switch.v1.TriggerEventResponseB\xf3\x01\n" +
	"\x1acom.hal.adapters.switch.v1B\vSwitchProtoP\x01ZKgithub.com/outshift-open/quantum-hal/sdk/go/hal/adapters/switch/v1;switchv1\xa2\x02\x03HAS\xaa\x02\x16Hal.Adapters.Switch.V1\xca\x02\x17Hal\\Adapters\\Switch_\\V1\xe2\x02#Hal\\Adapters\\Switch_\\V1\\GPBMetadata\xea\x02\x19Hal::Adapters::Switch::V1b\x06proto3"

var (
	file_hal_adapters_switch_v1_switch_proto_rawDescOnce sync.Once
	file_hal_adapters_switch_v1_switch_proto_rawDescData []byte
)

func file_hal_adapters_switch_v1_switch_proto_rawDescGZIP() []byte {
	file_hal_adapters_switch_v1_switch_proto_rawDescOnce.Do(func() {
		file_hal_adapters_switch_v1_switch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hal_adapters_switch_v1_switch_proto_rawDesc), len(file_hal_adapters_switch_v1_switch_proto_rawDesc)))
	})
	return file_hal_adapters_switch_v1_switch_proto_rawDescData
}

var file_hal_adapters_switch_v1_switch_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_hal_adapters_switch_v1_switch_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_hal_adapters_switch_v1_switch_proto_goTypes = []any{
	(SwitchState)(0),                       // 0: hal.adapters.switch.v1.SwitchState
	(*GetProductInfoRequest)(nil),          // 1: hal.adapters.switch.v1.GetProductInfoRequest
	(*GetProductInfoResponse)(nil),         // 2: hal.adapters.switch.v1.GetProductInfoResponse
	(*InitializeRequest)(nil),              // 3: hal.adapters.switch.v1.InitializeRequest
	(*InitializeResponse)(nil),             // 4: hal.adapters.switch.v1.InitializeResponse
	(*DeinitializeRequest)(nil),            // 5: hal.adapters.switch.v1.DeinitializeRequest
	(*DeinitializeResponse)(nil),           // 6: hal.adapters.switch.v1.DeinitializeResponse
	(*GetStatusRequest)(nil),               // 7: hal.adapters.switch.v1.GetStatusRequest
	(*GetStatusResponse)(nil),              // 8: hal.adapters.switch.v1.GetStatusResponse
	(*SetConfigRequest)(nil),               // 9: hal.adapters.switch.v1.SetConfigRequest
	(*SetConfigResponse)(nil),              // 10: hal.adapters.switch.v1.SetConfigResponse
	(*CommitConnectionRequest)(nil),        // 11: hal.adapters.switch.v1.CommitConnectionRequest
	(*CommitConnectionResponse)(nil),       // 12: hal.adapters.switch.v1.CommitConnectionResponse
	(*ClearConnectionsRequest)(nil),        // 13: hal.adapters.switch.v1.ClearConnectionsRequest
	(*ClearConnectionsResponse)(nil),       // 14: hal.adapters.switch.v1.ClearConnectionsResponse
	(*ExecuteCommandRequest)(nil),          // 15: hal.adapters.switch.v1.ExecuteCommandRequest
	(*ExecuteCommandResponse)(nil),         // 16: hal.adapters.switch.v1.ExecuteCommandResponse
	(*TriggerEventRequest)(nil),            // 17: hal.adapters.switch.v1.TriggerEventRequest
	(*TriggerEventResponse)(nil),           // 18: hal.adapters.switch.v1.TriggerEventResponse
	(*v1.HealthCheckRequest)(nil),          // 19: hal.adapters.common.v1.HealthCheckRequest
	(*v1.ResourceHealthCheckRequest)(nil),  // 20: hal.adapters.common.v1.ResourceHealthCheckRequest
	(*v1.AutoRecoverRequest)(nil),          // 21: hal.adapters.common.v1.AutoRecoverRequest
	(*v1.TuneRequest)(nil),                 // 22: hal.adapters.common.v1.TuneRequest
	(*v1.HealthCheckResponse)(nil),         // 23: hal.adapters.common.v1.HealthCheckResponse
	(*v1.ResourceHealthCheckResponse)(nil), // 24: hal.adapters.common.v1.ResourceHealthCheckResponse
	(*v1.AutoRecoverResponse)(nil),         // 25: hal.adapters.common.v1.AutoRecoverResponse
	(*v1.TuneResponse)(nil),                // 26: hal.adapters.common.v1.TuneResponse
}
var file_hal_adapters_switch_v1_switch_proto_depIdxs = []int32{
	0,  // 0: hal.adapters.switch.v1.GetStatusResponse.state:type_name -> hal.adapters.switch.v1.SwitchState
	19, // 1: hal.adapters.switch.v1.AdapterSwitchService.HealthCheck:input_type -> hal.adapters.common.v1.HealthCheckRequest
	20, // 2: hal.adapters.switch.v1.AdapterSwitchService.ResourceHealthCheck:input_type -> hal.adapters.common.v1.ResourceHealthCheckRequest
	1,  // 3: hal.adapters.switch.v1.AdapterSwitchService.GetProductInfo:input_type -> hal.adapters.switch.v1.GetProductInfoRequest
	3,  // 4: hal.adapters.switch.v1.AdapterSwitchService.Initialize:input_type -> hal.adapters.switch.v1.InitializeRequest
	5,  // 5: hal.adapters.switch.v1.AdapterSwitchService.Deinitialize:input_type -> hal.adapters.switch.v1.DeinitializeRequest
	7,  // 6: hal.adapters.switch.v1.AdapterSwitchService.GetStatus:input_type -> hal.adapters.switch.v1.GetStatusRequest
	9,  // 7: hal.adapters.switch.v1.AdapterSwitchService.SetConfig:input_type -> hal.adapters.switch.v1.SetConfigRequest
	21, // 8: hal.adapters.switch.v1.AdapterSwitchService.AutoRecover:input_type -> hal.adapters.common.v1.AutoRecoverRequest
	22, // 9: hal.adapters.switch.v1.AdapterSwitchService.Tune:input_type -> hal.adapters.common.v1.TuneRequest
	11, // 10: hal.adapters.switch.v1.AdapterSwitchService.CommitConnection:input_type -> hal.adapters.switch.v1.CommitConnectionRequest
	13, // 11: hal.adapters.switch.v1.AdapterSwitchService.ClearConnections:input_type -> hal.adapters.switch.v1.ClearConnectionsRequest
	15, // 12: hal.adapters.switch.v1.AdapterSwitchService.ExecuteCommand:input_type -> hal.adapters.switch.v1.ExecuteCommandRequest
	17, // 13: hal.adapters.switch.v1.AdapterSwitchService.TriggerEvent:input_type -> hal.adapters.switch.v1.TriggerEventRequest
	23, // 14: hal.adapters.switch.v1.AdapterSwitchService.HealthCheck:output_type -> hal.adapters.common.v1.HealthCheckResponse
	24, // 15: hal.adapters.switch.v1.AdapterSwitchService.ResourceHealthCheck:output_type -> hal.adapters.common.v1.ResourceHealthCheckResponse
	2,  // 16: hal.adapters.switch.v1.AdapterSwitchService.GetProductInfo:output_type -> hal.adapters.switch.v1.GetProductInfoResponse
	4,  // 17: hal.adapters.switch.v1.AdapterSwitchService.Initialize:output_type -> hal.adapters.switch.v1.InitializeResponse
	6,  // 18: hal.adapters.switch.v1.AdapterSwitchService.Deinitialize:output_type -> hal.adapters.switch.v1.DeinitializeResponse
	8,  // 19: hal.adapters.switch.v1.AdapterSwitchService.GetStatus:output_type -> hal.adapters.switch.v1.GetStatusResponse
	10, // 20: hal.adapters.switch.v1.AdapterSwitchService.SetConfig:output_type -> hal.adapters.switch.v1.SetConfigResponse
	25, // 21: hal.adapters.switch.v1.AdapterSwitchService.AutoRecover:output_type -> hal.adapters.common.v1.AutoRecoverResponse
	26, // 22: hal.adapters.switch.v1.AdapterSwitchService.Tune:output_type -> hal.adapters.common.v1.TuneResponse
	12, // 23: hal.adapters.switch.v1.AdapterSwitchService.CommitConnection:output_type -> hal.adapters.switch.v1.CommitConnectionResponse
	14, // 24: hal.adapters.switch.v1.AdapterSwitchService.ClearConnections:output_type -> hal.adapters.switch.v1.ClearConnectionsResponse
	16, // 25: hal.adapters.switch.v1.AdapterSwitchService.ExecuteCommand:output_type -> hal.adapters.switch.v1.ExecuteCommandResponse
	18, // 26: hal.adapters.switch.v1.AdapterSwitchService.TriggerEvent:output_type -> hal.adapters.switch.v1.TriggerEventResponse
	14, // [14:27] is the sub-list for method output_type
	1,  // [1:14] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_hal_adapters_switch_v1_switch_proto_init() }
func file_hal_adapters_switch_v1_switch_proto_init() {
	if File_hal_adapters_switch_v1_switch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hal_adapters_switch_v1_switch_proto_rawDesc), len(file_hal_adapters_switch_v1_switch_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hal_adapters_switch_v1_switch_proto_goTypes,
		DependencyIndexes: file_hal_adapters_switch_v1_switch_proto_depIdxs,
		EnumInfos:         file_hal_adapters_switch_v1_switch_proto_enumTypes,
		MessageInfos:      file_hal_adapters_switch_v1_switch_proto_msgTypes,
	}.Build()
	File_hal_adapters_switch_v1_switch_proto = out.File
	file_hal_adapters_switch_v1_switch_proto_goTypes = nil
	file_hal_adapters_switch_v1_switch_proto_depIdxs = nil
}
