// Copyright 2026 Cisco Systems, Inc. and its affiliates
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: hal/adapters/timetagger/v1/timetagger.proto

package timetaggerv1

import (
	context "context"
	v1 "github.com/outshift-open/quantum-hal/sdk/go/hal/adapters/common/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AdapterTimeTaggerService_HealthCheck_FullMethodName         = "/hal.adapters.timetagger.v1.AdapterTimeTaggerService/HealthCheck"
	AdapterTimeTaggerService_ResourceHealthCheck_FullMethodName = "/hal.adapters.timetagger.v1.AdapterTimeTaggerService/ResourceHealthCheck"
	AdapterTimeTaggerService_GetProductInfo_FullMethodName      = "/hal.adapters.timetagger.v1.AdapterTimeTaggerService/GetProductInfo"
	AdapterTimeTaggerService_Initialize_FullMethodName          = "/hal.adapters.timetagger.v1.AdapterTimeTaggerService/Initialize"
	AdapterTimeTaggerService_Deinitialize_FullMethodName        = "/hal.adapters.timetagger.v1.AdapterTimeTaggerService/Deinitialize"
	AdapterTimeTaggerService_GetStatus_FullMethodName           = "/hal.adapters.timetagger.v1.AdapterTimeTaggerService/GetStatus"
	AdapterTimeTaggerService_SetConfig_FullMethodName           = "/hal.adapters.timetagger.v1.AdapterTimeTaggerService/SetConfig"
	AdapterTimeTaggerService_AutoRecover_FullMethodName         = "/hal.adapters.timetagger.v1.AdapterTimeTaggerService/AutoRecover"
	AdapterTimeTaggerService_Tune_FullMethodName                = "/hal.adapters.timetagger.v1.AdapterTimeTaggerService/Tune"
	AdapterTimeTaggerService_StartDataCollection_FullMethodName = "/hal.adapters.timetagger.v1.AdapterTimeTaggerService/StartDataCollection"
	AdapterTimeTaggerService_StopDataCollection_FullMethodName  = "/hal.adapters.timetagger.v1.AdapterTimeTaggerService/StopDataCollection"
	AdapterTimeTaggerService_TriggerEvent_FullMethodName        = "/hal.adapters.timetagger.v1.AdapterTimeTaggerService/TriggerEvent"
)

// AdapterTimeTaggerServiceClient is the client API for AdapterTimeTaggerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdapterTimeTaggerServiceClient interface {
	// Liveness of the adapter process itself. See common.proto.
	HealthCheck(ctx context.Context, in *v1.HealthCheckRequest, opts ...grpc.CallOption) (*v1.HealthCheckResponse, error)
	// Health of the physical time-tagger hardware behind the adapter. See
	// common.proto; the UP / DOWN / DEGRADED-style result may be informed by
	// the device's current TimeTaggerState.
	ResourceHealthCheck(ctx context.Context, in *v1.ResourceHealthCheckRequest, opts ...grpc.CallOption) (*v1.ResourceHealthCheckResponse, error)
	// Static identity of the hardware behind the adapter: serial number,
	// vendor, firmware/software version.
	GetProductInfo(ctx context.Context, in *GetProductInfoRequest, opts ...grpc.CallOption) (*GetProductInfoResponse, error)
	// Brings the time tagger from a freshly power-cycled state to
	// ready-to-collect: connects to the device, loads calibration, and runs
	// whatever bring-up sequence the hardware needs. Not every product needs
	// preparation -- an adapter for hardware that's ready as soon as it's
	// powered on may implement this as an immediate no-op that reports READY.
	Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*InitializeResponse, error)
	// The opposite of Initialize: orderly shutdown once all jobs are done,
	// releasing whatever Initialize acquired (e.g. closing the device
	// connection). May also be a no-op where Initialize was.
	Deinitialize(ctx context.Context, in *DeinitializeRequest, opts ...grpc.CallOption) (*DeinitializeResponse, error)
	// Current lifecycle state of the time tagger, plus which run (if any) it
	// is bound to and its uptime. Poll this after Initialize/Deinitialize,
	// and during data collection.
	GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error)
	// Updates the time tagger's operating configuration without a full
	// Initialize/Deinitialize cycle.
	SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*SetConfigResponse, error)
	// Attempts the adapter's built-in automated recovery sequence to bring
	// the time tagger back from TIME_TAGGER_STATE_DEGRADED (or FAULT) toward
	// READY -- e.g. reconnecting to the device or re-loading calibration. See
	// common.proto. Not every product needs a real recovery sequence -- an
	// adapter may implement this as an immediate no-op, same as Initialize.
	AutoRecover(ctx context.Context, in *v1.AutoRecoverRequest, opts ...grpc.CallOption) (*v1.AutoRecoverResponse, error)
	// Applies a single targeted adjustment as an alternative to a full
	// AutoRecover sequence -- e.g. re-calibrate one channel rather than the
	// whole device. See common.proto. Vendor-specific; adapters with no such
	// fine-grained control may return UNIMPLEMENTED.
	Tune(ctx context.Context, in *v1.TuneRequest, opts ...grpc.CallOption) (*v1.TuneResponse, error)
	// Starts recording detector-click data for the given run. Called when the
	// controller begins a job that needs timing/coincidence data (e.g. a
	// heralding or QBER measurement). Requires TIME_TAGGER_STATE_READY; moves
	// the time tagger into TIME_TAGGER_STATE_COLLECTING for the duration of
	// the run. Vendor-specific measurement parameters (which channels,
	// coincidence window, per-channel delays, where results are written,
	// etc.) go in config_json.
	StartDataCollection(ctx context.Context, in *StartDataCollectionRequest, opts ...grpc.CallOption) (*StartDataCollectionResponse, error)
	// Stops recording detector-click data for the given run and returns the
	// time tagger to TIME_TAGGER_STATE_READY, available for the next run.
	StopDataCollection(ctx context.Context, in *StopDataCollectionRequest, opts ...grpc.CallOption) (*StopDataCollectionResponse, error)
	// Triggers a special emulation/test condition for a running run -- e.g. a
	// simulated eavesdropper, an induced fault, or an environmental
	// perturbation. Not part of normal operation: an adapter with no such
	// capability may return UNIMPLEMENTED.
	TriggerEvent(ctx context.Context, in *TriggerEventRequest, opts ...grpc.CallOption) (*TriggerEventResponse, error)
}

type adapterTimeTaggerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdapterTimeTaggerServiceClient(cc grpc.ClientConnInterface) AdapterTimeTaggerServiceClient {
	return &adapterTimeTaggerServiceClient{cc}
}

func (c *adapterTimeTaggerServiceClient) HealthCheck(ctx context.Context, in *v1.HealthCheckRequest, opts ...grpc.CallOption) (*v1.HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.HealthCheckResponse)
	err := c.cc.Invoke(ctx, AdapterTimeTaggerService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterTimeTaggerServiceClient) ResourceHealthCheck(ctx context.Context, in *v1.ResourceHealthCheckRequest, opts ...grpc.CallOption) (*v1.ResourceHealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.ResourceHealthCheckResponse)
	err := c.cc.Invoke(ctx, AdapterTimeTaggerService_ResourceHealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterTimeTaggerServiceClient) GetProductInfo(ctx context.Context, in *GetProductInfoRequest, opts ...grpc.CallOption) (*GetProductInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductInfoResponse)
	err := c.cc.Invoke(ctx, AdapterTimeTaggerService_GetProductInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterTimeTaggerServiceClient) Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (*InitializeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitializeResponse)
	err := c.cc.Invoke(ctx, AdapterTimeTaggerService_Initialize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterTimeTaggerServiceClient) Deinitialize(ctx context.Context, in *DeinitializeRequest, opts ...grpc.CallOption) (*DeinitializeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeinitializeResponse)
	err := c.cc.Invoke(ctx, AdapterTimeTaggerService_Deinitialize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterTimeTaggerServiceClient) GetStatus(ctx context.Context, in *GetStatusRequest, opts ...grpc.CallOption) (*GetStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatusResponse)
	err := c.cc.Invoke(ctx, AdapterTimeTaggerService_GetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterTimeTaggerServiceClient) SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*SetConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetConfigResponse)
	err := c.cc.Invoke(ctx, AdapterTimeTaggerService_SetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterTimeTaggerServiceClient) AutoRecover(ctx context.Context, in *v1.AutoRecoverRequest, opts ...grpc.CallOption) (*v1.AutoRecoverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.AutoRecoverResponse)
	err := c.cc.Invoke(ctx, AdapterTimeTaggerService_AutoRecover_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterTimeTaggerServiceClient) Tune(ctx context.Context, in *v1.TuneRequest, opts ...grpc.CallOption) (*v1.TuneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1.TuneResponse)
	err := c.cc.Invoke(ctx, AdapterTimeTaggerService_Tune_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterTimeTaggerServiceClient) StartDataCollection(ctx context.Context, in *StartDataCollectionRequest, opts ...grpc.CallOption) (*StartDataCollectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartDataCollectionResponse)
	err := c.cc.Invoke(ctx, AdapterTimeTaggerService_StartDataCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterTimeTaggerServiceClient) StopDataCollection(ctx context.Context, in *StopDataCollectionRequest, opts ...grpc.CallOption) (*StopDataCollectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopDataCollectionResponse)
	err := c.cc.Invoke(ctx, AdapterTimeTaggerService_StopDataCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adapterTimeTaggerServiceClient) TriggerEvent(ctx context.Context, in *TriggerEventRequest, opts ...grpc.CallOption) (*TriggerEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerEventResponse)
	err := c.cc.Invoke(ctx, AdapterTimeTaggerService_TriggerEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdapterTimeTaggerServiceServer is the server API for AdapterTimeTaggerService service.
// All implementations must embed UnimplementedAdapterTimeTaggerServiceServer
// for forward compatibility.
type AdapterTimeTaggerServiceServer interface {
	// Liveness of the adapter process itself. See common.proto.
	HealthCheck(context.Context, *v1.HealthCheckRequest) (*v1.HealthCheckResponse, error)
	// Health of the physical time-tagger hardware behind the adapter. See
	// common.proto; the UP / DOWN / DEGRADED-style result may be informed by
	// the device's current TimeTaggerState.
	ResourceHealthCheck(context.Context, *v1.ResourceHealthCheckRequest) (*v1.ResourceHealthCheckResponse, error)
	// Static identity of the hardware behind the adapter: serial number,
	// vendor, firmware/software version.
	GetProductInfo(context.Context, *GetProductInfoRequest) (*GetProductInfoResponse, error)
	// Brings the time tagger from a freshly power-cycled state to
	// ready-to-collect: connects to the device, loads calibration, and runs
	// whatever bring-up sequence the hardware needs. Not every product needs
	// preparation -- an adapter for hardware that's ready as soon as it's
	// powered on may implement this as an immediate no-op that reports READY.
	Initialize(context.Context, *InitializeRequest) (*InitializeResponse, error)
	// The opposite of Initialize: orderly shutdown once all jobs are done,
	// releasing whatever Initialize acquired (e.g. closing the device
	// connection). May also be a no-op where Initialize was.
	Deinitialize(context.Context, *DeinitializeRequest) (*DeinitializeResponse, error)
	// Current lifecycle state of the time tagger, plus which run (if any) it
	// is bound to and its uptime. Poll this after Initialize/Deinitialize,
	// and during data collection.
	GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error)
	// Updates the time tagger's operating configuration without a full
	// Initialize/Deinitialize cycle.
	SetConfig(context.Context, *SetConfigRequest) (*SetConfigResponse, error)
	// Attempts the adapter's built-in automated recovery sequence to bring
	// the time tagger back from TIME_TAGGER_STATE_DEGRADED (or FAULT) toward
	// READY -- e.g. reconnecting to the device or re-loading calibration. See
	// common.proto. Not every product needs a real recovery sequence -- an
	// adapter may implement this as an immediate no-op, same as Initialize.
	AutoRecover(context.Context, *v1.AutoRecoverRequest) (*v1.AutoRecoverResponse, error)
	// Applies a single targeted adjustment as an alternative to a full
	// AutoRecover sequence -- e.g. re-calibrate one channel rather than the
	// whole device. See common.proto. Vendor-specific; adapters with no such
	// fine-grained control may return UNIMPLEMENTED.
	Tune(context.Context, *v1.TuneRequest) (*v1.TuneResponse, error)
	// Starts recording detector-click data for the given run. Called when the
	// controller begins a job that needs timing/coincidence data (e.g. a
	// heralding or QBER measurement). Requires TIME_TAGGER_STATE_READY; moves
	// the time tagger into TIME_TAGGER_STATE_COLLECTING for the duration of
	// the run. Vendor-specific measurement parameters (which channels,
	// coincidence window, per-channel delays, where results are written,
	// etc.) go in config_json.
	StartDataCollection(context.Context, *StartDataCollectionRequest) (*StartDataCollectionResponse, error)
	// Stops recording detector-click data for the given run and returns the
	// time tagger to TIME_TAGGER_STATE_READY, available for the next run.
	StopDataCollection(context.Context, *StopDataCollectionRequest) (*StopDataCollectionResponse, error)
	// Triggers a special emulation/test condition for a running run -- e.g. a
	// simulated eavesdropper, an induced fault, or an environmental
	// perturbation. Not part of normal operation: an adapter with no such
	// capability may return UNIMPLEMENTED.
	TriggerEvent(context.Context, *TriggerEventRequest) (*TriggerEventResponse, error)
	mustEmbedUnimplementedAdapterTimeTaggerServiceServer()
}

// UnimplementedAdapterTimeTaggerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAdapterTimeTaggerServiceServer struct{}

func (UnimplementedAdapterTimeTaggerServiceServer) HealthCheck(context.Context, *v1.HealthCheckRequest) (*v1.HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedAdapterTimeTaggerServiceServer) ResourceHealthCheck(context.Context, *v1.ResourceHealthCheckRequest) (*v1.ResourceHealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResourceHealthCheck not implemented")
}
func (UnimplementedAdapterTimeTaggerServiceServer) GetProductInfo(context.Context, *GetProductInfoRequest) (*GetProductInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProductInfo not implemented")
}
func (UnimplementedAdapterTimeTaggerServiceServer) Initialize(context.Context, *InitializeRequest) (*InitializeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Initialize not implemented")
}
func (UnimplementedAdapterTimeTaggerServiceServer) Deinitialize(context.Context, *DeinitializeRequest) (*DeinitializeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Deinitialize not implemented")
}
func (UnimplementedAdapterTimeTaggerServiceServer) GetStatus(context.Context, *GetStatusRequest) (*GetStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatus not implemented")
}
func (UnimplementedAdapterTimeTaggerServiceServer) SetConfig(context.Context, *SetConfigRequest) (*SetConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetConfig not implemented")
}
func (UnimplementedAdapterTimeTaggerServiceServer) AutoRecover(context.Context, *v1.AutoRecoverRequest) (*v1.AutoRecoverResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AutoRecover not implemented")
}
func (UnimplementedAdapterTimeTaggerServiceServer) Tune(context.Context, *v1.TuneRequest) (*v1.TuneResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Tune not implemented")
}
func (UnimplementedAdapterTimeTaggerServiceServer) StartDataCollection(context.Context, *StartDataCollectionRequest) (*StartDataCollectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartDataCollection not implemented")
}
func (UnimplementedAdapterTimeTaggerServiceServer) StopDataCollection(context.Context, *StopDataCollectionRequest) (*StopDataCollectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopDataCollection not implemented")
}
func (UnimplementedAdapterTimeTaggerServiceServer) TriggerEvent(context.Context, *TriggerEventRequest) (*TriggerEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TriggerEvent not implemented")
}
func (UnimplementedAdapterTimeTaggerServiceServer) mustEmbedUnimplementedAdapterTimeTaggerServiceServer() {
}
func (UnimplementedAdapterTimeTaggerServiceServer) testEmbeddedByValue() {}

// UnsafeAdapterTimeTaggerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdapterTimeTaggerServiceServer will
// result in compilation errors.
type UnsafeAdapterTimeTaggerServiceServer interface {
	mustEmbedUnimplementedAdapterTimeTaggerServiceServer()
}

func RegisterAdapterTimeTaggerServiceServer(s grpc.ServiceRegistrar, srv AdapterTimeTaggerServiceServer) {
	// If the following call panics, it indicates UnimplementedAdapterTimeTaggerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AdapterTimeTaggerService_ServiceDesc, srv)
}

func _AdapterTimeTaggerService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterTimeTaggerServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterTimeTaggerService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterTimeTaggerServiceServer).HealthCheck(ctx, req.(*v1.HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterTimeTaggerService_ResourceHealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.ResourceHealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterTimeTaggerServiceServer).ResourceHealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterTimeTaggerService_ResourceHealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterTimeTaggerServiceServer).ResourceHealthCheck(ctx, req.(*v1.ResourceHealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterTimeTaggerService_GetProductInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterTimeTaggerServiceServer).GetProductInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterTimeTaggerService_GetProductInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterTimeTaggerServiceServer).GetProductInfo(ctx, req.(*GetProductInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterTimeTaggerService_Initialize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitializeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterTimeTaggerServiceServer).Initialize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterTimeTaggerService_Initialize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterTimeTaggerServiceServer).Initialize(ctx, req.(*InitializeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterTimeTaggerService_Deinitialize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeinitializeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterTimeTaggerServiceServer).Deinitialize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterTimeTaggerService_Deinitialize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterTimeTaggerServiceServer).Deinitialize(ctx, req.(*DeinitializeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterTimeTaggerService_GetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterTimeTaggerServiceServer).GetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterTimeTaggerService_GetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterTimeTaggerServiceServer).GetStatus(ctx, req.(*GetStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterTimeTaggerService_SetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterTimeTaggerServiceServer).SetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterTimeTaggerService_SetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterTimeTaggerServiceServer).SetConfig(ctx, req.(*SetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterTimeTaggerService_AutoRecover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.AutoRecoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterTimeTaggerServiceServer).AutoRecover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterTimeTaggerService_AutoRecover_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterTimeTaggerServiceServer).AutoRecover(ctx, req.(*v1.AutoRecoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterTimeTaggerService_Tune_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.TuneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterTimeTaggerServiceServer).Tune(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterTimeTaggerService_Tune_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterTimeTaggerServiceServer).Tune(ctx, req.(*v1.TuneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterTimeTaggerService_StartDataCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartDataCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterTimeTaggerServiceServer).StartDataCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterTimeTaggerService_StartDataCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterTimeTaggerServiceServer).StartDataCollection(ctx, req.(*StartDataCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterTimeTaggerService_StopDataCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopDataCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterTimeTaggerServiceServer).StopDataCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterTimeTaggerService_StopDataCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterTimeTaggerServiceServer).StopDataCollection(ctx, req.(*StopDataCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdapterTimeTaggerService_TriggerEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdapterTimeTaggerServiceServer).TriggerEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdapterTimeTaggerService_TriggerEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdapterTimeTaggerServiceServer).TriggerEvent(ctx, req.(*TriggerEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AdapterTimeTaggerService_ServiceDesc is the grpc.ServiceDesc for AdapterTimeTaggerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdapterTimeTaggerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hal.adapters.timetagger.v1.AdapterTimeTaggerService",
	HandlerType: (*AdapterTimeTaggerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _AdapterTimeTaggerService_HealthCheck_Handler,
		},
		{
			MethodName: "ResourceHealthCheck",
			Handler:    _AdapterTimeTaggerService_ResourceHealthCheck_Handler,
		},
		{
			MethodName: "GetProductInfo",
			Handler:    _AdapterTimeTaggerService_GetProductInfo_Handler,
		},
		{
			MethodName: "Initialize",
			Handler:    _AdapterTimeTaggerService_Initialize_Handler,
		},
		{
			MethodName: "Deinitialize",
			Handler:    _AdapterTimeTaggerService_Deinitialize_Handler,
		},
		{
			MethodName: "GetStatus",
			Handler:    _AdapterTimeTaggerService_GetStatus_Handler,
		},
		{
			MethodName: "SetConfig",
			Handler:    _AdapterTimeTaggerService_SetConfig_Handler,
		},
		{
			MethodName: "AutoRecover",
			Handler:    _AdapterTimeTaggerService_AutoRecover_Handler,
		},
		{
			MethodName: "Tune",
			Handler:    _AdapterTimeTaggerService_Tune_Handler,
		},
		{
			MethodName: "StartDataCollection",
			Handler:    _AdapterTimeTaggerService_StartDataCollection_Handler,
		},
		{
			MethodName: "StopDataCollection",
			Handler:    _AdapterTimeTaggerService_StopDataCollection_Handler,
		},
		{
			MethodName: "TriggerEvent",
			Handler:    _AdapterTimeTaggerService_TriggerEvent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hal/adapters/timetagger/v1/timetagger.proto",
}
