// Copyright 2026 Cisco Systems, Inc. and its affiliates
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: hal/adapters/timetagger/v1/timetagger.proto

package timetaggerv1

import (
	v1 "github.com/outshift-open/quantum-hal/sdk/go/hal/adapters/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Lifecycle of the time-tagger hardware.
type TimeTaggerState int32

const (
	TimeTaggerState_TIME_TAGGER_STATE_UNSPECIFIED TimeTaggerState = 0
	// Powered, not yet initialized -- the OFF of the state machine.
	TimeTaggerState_TIME_TAGGER_STATE_IDLE TimeTaggerState = 1
	// Connecting to the device and/or loading calibration.
	TimeTaggerState_TIME_TAGGER_STATE_INITIALIZING TimeTaggerState = 2
	// Ready to accept StartDataCollection.
	TimeTaggerState_TIME_TAGGER_STATE_READY TimeTaggerState = 3
	// Actively recording detector-click data for the run bound via
	// StartDataCollection; not available for a new run until
	// StopDataCollection returns it to READY.
	TimeTaggerState_TIME_TAGGER_STATE_COLLECTING     TimeTaggerState = 4
	TimeTaggerState_TIME_TAGGER_STATE_FAULT          TimeTaggerState = 5
	TimeTaggerState_TIME_TAGGER_STATE_DEINITIALIZING TimeTaggerState = 6
	// Collecting, but at least one channel is outside tolerance (e.g. noisy
	// or reporting an out-of-spec count rate).
	TimeTaggerState_TIME_TAGGER_STATE_DEGRADED TimeTaggerState = 7
)

// Enum value maps for TimeTaggerState.
var (
	TimeTaggerState_name = map[int32]string{
		0: "TIME_TAGGER_STATE_UNSPECIFIED",
		1: "TIME_TAGGER_STATE_IDLE",
		2: "TIME_TAGGER_STATE_INITIALIZING",
		3: "TIME_TAGGER_STATE_READY",
		4: "TIME_TAGGER_STATE_COLLECTING",
		5: "TIME_TAGGER_STATE_FAULT",
		6: "TIME_TAGGER_STATE_DEINITIALIZING",
		7: "TIME_TAGGER_STATE_DEGRADED",
	}
	TimeTaggerState_value = map[string]int32{
		"TIME_TAGGER_STATE_UNSPECIFIED":    0,
		"TIME_TAGGER_STATE_IDLE":           1,
		"TIME_TAGGER_STATE_INITIALIZING":   2,
		"TIME_TAGGER_STATE_READY":          3,
		"TIME_TAGGER_STATE_COLLECTING":     4,
		"TIME_TAGGER_STATE_FAULT":          5,
		"TIME_TAGGER_STATE_DEINITIALIZING": 6,
		"TIME_TAGGER_STATE_DEGRADED":       7,
	}
)

func (x TimeTaggerState) Enum() *TimeTaggerState {
	p := new(TimeTaggerState)
	*p = x
	return p
}

func (x TimeTaggerState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimeTaggerState) Descriptor() protoreflect.EnumDescriptor {
	return file_hal_adapters_timetagger_v1_timetagger_proto_enumTypes[0].Descriptor()
}

func (TimeTaggerState) Type() protoreflect.EnumType {
	return &file_hal_adapters_timetagger_v1_timetagger_proto_enumTypes[0]
}

func (x TimeTaggerState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TimeTaggerState.Descriptor instead.
func (TimeTaggerState) EnumDescriptor() ([]byte, []int) {
	return file_hal_adapters_timetagger_v1_timetagger_proto_rawDescGZIP(), []int{0}
}

type GetProductInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ResourceType  string                 `protobuf:"bytes,2,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductInfoRequest) Reset() {
	*x = GetProductInfoRequest{}
	mi := &file_hal_adapters_timetagger_v1_timetagger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductInfoRequest) ProtoMessage() {}

func (x *GetProductInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_timetagger_v1_timetagger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductInfoRequest.ProtoReflect.Descriptor instead.
func (*GetProductInfoRequest) Descriptor() ([]byte, []int) {
	return file_hal_adapters_timetagger_v1_timetagger_proto_rawDescGZIP(), []int{0}
}

func (x *GetProductInfoRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *GetProductInfoRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

type GetProductInfoResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SerialNumber    string                 `protobuf:"bytes,1,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	ProductCode     string                 `protobuf:"bytes,2,opt,name=product_code,json=productCode,proto3" json:"product_code,omitempty"`
	SoftwareVersion string                 `protobuf:"bytes,3,opt,name=software_version,json=softwareVersion,proto3" json:"software_version,omitempty"`
	Vendor          string                 `protobuf:"bytes,4,opt,name=vendor,proto3" json:"vendor,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetProductInfoResponse) Reset() {
	*x = GetProductInfoResponse{}
	mi := &file_hal_adapters_timetagger_v1_timetagger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductInfoResponse) ProtoMessage() {}

func (x *GetProductInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_timetagger_v1_timetagger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductInfoResponse.ProtoReflect.Descriptor instead.
func (*GetProductInfoResponse) Descriptor() ([]byte, []int) {
	return file_hal_adapters_timetagger_v1_timetagger_proto_rawDescGZIP(), []int{1}
}

func (x *GetProductInfoResponse) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *GetProductInfoResponse) GetProductCode() string {
	if x != nil {
		return x.ProductCode
	}
	return ""
}

func (x *GetProductInfoResponse) GetSoftwareVersion() string {
	if x != nil {
		return x.SoftwareVersion
	}
	return ""
}

func (x *GetProductInfoResponse) GetVendor() string {
	if x != nil {
		return x.Vendor
	}
	return ""
}

// Vendor-specific bring-up parameters, if a given product needs any (e.g.
// calibration data, a device connection string). Encoded as a JSON object;
// each product's adapter implementation defines and documents its own
// schema and is responsible for parsing it. Leave empty if the product
// needs no configuration to initialize.
type InitializeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ConfigJson    string                 `protobuf:"bytes,2,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	ResourceType  string                 `protobuf:"bytes,3,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeRequest) Reset() {
	*x = InitializeRequest{}
	mi := &file_hal_adapters_timetagger_v1_timetagger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeRequest) ProtoMessage() {}

func (x *InitializeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_timetagger_v1_timetagger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeRequest.ProtoReflect.Descriptor instead.
func (*InitializeRequest) Descriptor() ([]byte, []int) {
	return file_hal_adapters_timetagger_v1_timetagger_proto_rawDescGZIP(), []int{2}
}

func (x *InitializeRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *InitializeRequest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

func (x *InitializeRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

type InitializeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitializeResponse) Reset() {
	*x = InitializeResponse{}
	mi := &file_hal_adapters_timetagger_v1_timetagger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitializeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitializeResponse) ProtoMessage() {}

func (x *InitializeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_timetagger_v1_timetagger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitializeResponse.ProtoReflect.Descriptor instead.
func (*InitializeResponse) Descriptor() ([]byte, []int) {
	return file_hal_adapters_timetagger_v1_timetagger_proto_rawDescGZIP(), []int{3}
}

func (x *InitializeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeinitializeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ResourceType  string                 `protobuf:"bytes,2,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeinitializeRequest) Reset() {
	*x = DeinitializeRequest{}
	mi := &file_hal_adapters_timetagger_v1_timetagger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeinitializeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeinitializeRequest) ProtoMessage() {}

func (x *DeinitializeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_timetagger_v1_timetagger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeinitializeRequest.ProtoReflect.Descriptor instead.
func (*DeinitializeRequest) Descriptor() ([]byte, []int) {
	return file_hal_adapters_timetagger_v1_timetagger_proto_rawDescGZIP(), []int{4}
}

func (x *DeinitializeRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *DeinitializeRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

type DeinitializeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeinitializeResponse) Reset() {
	*x = DeinitializeResponse{}
	mi := &file_hal_adapters_timetagger_v1_timetagger_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeinitializeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeinitializeResponse) ProtoMessage() {}

func (x *DeinitializeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_timetagger_v1_timetagger_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeinitializeResponse.ProtoReflect.Descriptor instead.
func (*DeinitializeResponse) Descriptor() ([]byte, []int) {
	return file_hal_adapters_timetagger_v1_timetagger_proto_rawDescGZIP(), []int{5}
}

func (x *DeinitializeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ResourceType  string                 `protobuf:"bytes,2,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_hal_adapters_timetagger_v1_timetagger_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_timetagger_v1_timetagger_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_hal_adapters_timetagger_v1_timetagger_proto_rawDescGZIP(), []int{6}
}

func (x *GetStatusRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *GetStatusRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	State         TimeTaggerState        `protobuf:"varint,1,opt,name=state,proto3,enum=hal.adapters.timetagger.v1.TimeTaggerState" json:"state,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	UptimeSeconds float32                `protobuf:"fixed32,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	// Vendor-specific status detail beyond the common TimeTaggerState (e.g.
	// per-channel count rates, temperature). Encoded as a JSON object; each
	// product's adapter implementation defines and documents its own schema
	// for it.
	StatusJson    string `protobuf:"bytes,4,opt,name=status_json,json=statusJson,proto3" json:"status_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_hal_adapters_timetagger_v1_timetagger_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_timetagger_v1_timetagger_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_hal_adapters_timetagger_v1_timetagger_proto_rawDescGZIP(), []int{7}
}

func (x *GetStatusResponse) GetState() TimeTaggerState {
	if x != nil {
		return x.State
	}
	return TimeTaggerState_TIME_TAGGER_STATE_UNSPECIFIED
}

func (x *GetStatusResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *GetStatusResponse) GetUptimeSeconds() float32 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *GetStatusResponse) GetStatusJson() string {
	if x != nil {
		return x.StatusJson
	}
	return ""
}

type SetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	ConfigJson    string                 `protobuf:"bytes,2,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	ResourceType  string                 `protobuf:"bytes,3,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConfigRequest) Reset() {
	*x = SetConfigRequest{}
	mi := &file_hal_adapters_timetagger_v1_timetagger_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConfigRequest) ProtoMessage() {}

func (x *SetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_timetagger_v1_timetagger_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConfigRequest.ProtoReflect.Descriptor instead.
func (*SetConfigRequest) Descriptor() ([]byte, []int) {
	return file_hal_adapters_timetagger_v1_timetagger_proto_rawDescGZIP(), []int{8}
}

func (x *SetConfigRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *SetConfigRequest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

func (x *SetConfigRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

type SetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetConfigResponse) Reset() {
	*x = SetConfigResponse{}
	mi := &file_hal_adapters_timetagger_v1_timetagger_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetConfigResponse) ProtoMessage() {}

func (x *SetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_timetagger_v1_timetagger_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetConfigResponse.ProtoReflect.Descriptor instead.
func (*SetConfigResponse) Descriptor() ([]byte, []int) {
	return file_hal_adapters_timetagger_v1_timetagger_proto_rawDescGZIP(), []int{9}
}

func (x *SetConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Vendor-specific data-collection configuration (measurement type(s),
// channel mapping, coincidence window, bulk delays, where results are
// written, etc. -- whatever a given product needs). This spec doesn't model
// those fields: each product's adapter implementation defines and documents
// its own JSON schema for config_json and is responsible for parsing it.
type StartDataCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	ConfigJson    string                 `protobuf:"bytes,3,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	ResourceType  string                 `protobuf:"bytes,4,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartDataCollectionRequest) Reset() {
	*x = StartDataCollectionRequest{}
	mi := &file_hal_adapters_timetagger_v1_timetagger_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartDataCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartDataCollectionRequest) ProtoMessage() {}

func (x *StartDataCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_timetagger_v1_timetagger_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartDataCollectionRequest.ProtoReflect.Descriptor instead.
func (*StartDataCollectionRequest) Descriptor() ([]byte, []int) {
	return file_hal_adapters_timetagger_v1_timetagger_proto_rawDescGZIP(), []int{10}
}

func (x *StartDataCollectionRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *StartDataCollectionRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *StartDataCollectionRequest) GetConfigJson() string {
	if x != nil {
		return x.ConfigJson
	}
	return ""
}

func (x *StartDataCollectionRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

type StartDataCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartDataCollectionResponse) Reset() {
	*x = StartDataCollectionResponse{}
	mi := &file_hal_adapters_timetagger_v1_timetagger_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartDataCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartDataCollectionResponse) ProtoMessage() {}

func (x *StartDataCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_timetagger_v1_timetagger_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartDataCollectionResponse.ProtoReflect.Descriptor instead.
func (*StartDataCollectionResponse) Descriptor() ([]byte, []int) {
	return file_hal_adapters_timetagger_v1_timetagger_proto_rawDescGZIP(), []int{11}
}

func (x *StartDataCollectionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StopDataCollectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	ResourceType  string                 `protobuf:"bytes,3,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopDataCollectionRequest) Reset() {
	*x = StopDataCollectionRequest{}
	mi := &file_hal_adapters_timetagger_v1_timetagger_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopDataCollectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopDataCollectionRequest) ProtoMessage() {}

func (x *StopDataCollectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_timetagger_v1_timetagger_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopDataCollectionRequest.ProtoReflect.Descriptor instead.
func (*StopDataCollectionRequest) Descriptor() ([]byte, []int) {
	return file_hal_adapters_timetagger_v1_timetagger_proto_rawDescGZIP(), []int{12}
}

func (x *StopDataCollectionRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *StopDataCollectionRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *StopDataCollectionRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

type StopDataCollectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopDataCollectionResponse) Reset() {
	*x = StopDataCollectionResponse{}
	mi := &file_hal_adapters_timetagger_v1_timetagger_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopDataCollectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopDataCollectionResponse) ProtoMessage() {}

func (x *StopDataCollectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_timetagger_v1_timetagger_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopDataCollectionResponse.ProtoReflect.Descriptor instead.
func (*StopDataCollectionResponse) Descriptor() ([]byte, []int) {
	return file_hal_adapters_timetagger_v1_timetagger_proto_rawDescGZIP(), []int{13}
}

func (x *StopDataCollectionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// event_type names which emulation/test condition to trigger (e.g.
// "eavesdropper", "fault", ...) -- adapter- and product-defined, not
// enumerated here. payload_json carries whatever parameters that event type
// needs, encoded as a JSON object, per a schema the adapter implementation
// defines and documents for that event_type.
type TriggerEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,4,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	ResourceType  string                 `protobuf:"bytes,5,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerEventRequest) Reset() {
	*x = TriggerEventRequest{}
	mi := &file_hal_adapters_timetagger_v1_timetagger_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerEventRequest) ProtoMessage() {}

func (x *TriggerEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_timetagger_v1_timetagger_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerEventRequest.ProtoReflect.Descriptor instead.
func (*TriggerEventRequest) Descriptor() ([]byte, []int) {
	return file_hal_adapters_timetagger_v1_timetagger_proto_rawDescGZIP(), []int{14}
}

func (x *TriggerEventRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *TriggerEventRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *TriggerEventRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *TriggerEventRequest) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

func (x *TriggerEventRequest) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

type TriggerEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerEventResponse) Reset() {
	*x = TriggerEventResponse{}
	mi := &file_hal_adapters_timetagger_v1_timetagger_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerEventResponse) ProtoMessage() {}

func (x *TriggerEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hal_adapters_timetagger_v1_timetagger_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerEventResponse.ProtoReflect.Descriptor instead.
func (*TriggerEventResponse) Descriptor() ([]byte, []int) {
	return file_hal_adapters_timetagger_v1_timetagger_proto_rawDescGZIP(), []int{15}
}

func (x *TriggerEventResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_hal_adapters_timetagger_v1_timetagger_proto protoreflect.FileDescriptor

const file_hal_adapters_timetagger_v1_timetagger_proto_rawDesc = "" +
	"\n" +
	"+hal/adapters/timetagger/v1/timetagger.proto\x12\x1ahal.adapters.timetagger.v1\x1a#hal/adapters/common/v1/common.proto\"[\n" +
	"\x15GetProductInfoRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12#\n" +
	"\rresource_type\x18\x02 \x01(\tR\fresourceType\"\xa3\x01\n" +
	"\x16GetProductInfoResponse\x12#\n" +
	"\rserial_number\x18\x01 \x01(\tR\fserialNumber\x12!\n" +
	"\fproduct_code\x18\x02 \x01(\tR\vproductCode\x12)\n" +
	"\x10software_version\x18\x03 \x01(\tR\x0fsoftwareVersion\x12\x16\n" +
	"\x06vendor\x18\x04 \x01(\tR\x06vendor\"x\n" +
	"\x11InitializeRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1f\n" +
	"\vconfig_json\x18\x02 \x01(\tR\n" +
	"configJson\x12#\n" +
	"\rresource_type\x18\x03 \x01(\tR\fresourceType\".\n" +
	"\x12InitializeResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"Y\n" +
	"\x13DeinitializeRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12#\n" +
	"\rresource_type\x18\x02 \x01(\tR\fresourceType\"0\n" +
	"\x14DeinitializeResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"V\n" +
	"\x10GetStatusRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12#\n" +
	"\rresource_type\x18\x02 \x01(\tR\fresourceType\"\xb5\x01\n" +
	"\x11GetStatusResponse\x12A\n" +
	"\x05state\x18\x01 \x01(\x0e2+.hal.adapters.timetagger.v1.TimeTaggerStateR\x05state\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x02R\ruptimeSeconds\x12\x1f\n" +
	"\vstatus_json\x18\x04 \x01(\tR\n" +
	"statusJson\"w\n" +
	"\x10SetConfigRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x1f\n" +
	"\vconfig_json\x18\x02 \x01(\tR\n" +
	"configJson\x12#\n" +
	"\rresource_type\x18\x03 \x01(\tR\fresourceType\"-\n" +
	"\x11SetConfigResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x98\x01\n" +
	"\x1aStartDataCollectionRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x1f\n" +
	"\vconfig_json\x18\x03 \x01(\tR\n" +
	"configJson\x12#\n" +
	"\rresource_type\x18\x04 \x01(\tR\fresourceType\"7\n" +
	"\x1bStartDataCollectionResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"v\n" +
	"\x19StopDataCollectionRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12#\n" +
	"\rresource_type\x18\x03 \x01(\tR\fresourceType\"6\n" +
	"\x1aStopDataCollectionResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xb2\x01\n" +
	"\x13TriggerEventRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\x12!\n" +
	"\fpayload_json\x18\x04 \x01(\tR\vpayloadJson\x12#\n" +
	"\rresource_type\x18\x05 \x01(\tR\fresourceType\"0\n" +
	"\x14TriggerEventResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage*\x96\x02\n" +
	"\x0fTimeTaggerState\x12!\n" +
	"\x1dTIME_TAGGER_STATE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16TIME_TAGGER_STATE_IDLE\x10\x01\x12\"\n" +
	"\x1eTIME_TAGGER_STATE_INITIALIZING\x10\x02\x12\x1b\n" +
	"\x17TIME_TAGGER_STATE_READY\x10\x03\x12 \n" +
	"\x1cTIME_TAGGER_STATE_COLLECTING\x10\x04\x12\x1b\n" +
	"\x17TIME_TAGGER_STATE_FAULT\x10\x05\x12$\n" +
	" TIME_TAGGER_STATE_DEINITIALIZING\x10\x06\x12\x1e\n" +
	"\x1aTIME_TAGGER_STATE_DEGRADED\x10\a2\xec\n" +
	"\n" +
	"\x18AdapterTimeTaggerService\x12f\n" +
	"\vHealthCheck\x12*.hal.adapters.common.v1.HealthCheckRequest\x1a+.hal.adapters.common.v1.HealthCheckResponse\x12~\n" +
	"\x13ResourceHealthCheck\x122.hal.adapters.common.v1.ResourceHealthCheckRequest\x1a3.hal.adapters.common.v1.ResourceHealthCheckResponse\x12w\n" +
	"\x0eGetProductInfo\x121.hal.adapters.timetagger.v1.GetProductInfoRequest\x1a2.hal.adapters.timetagger.v1.GetProductInfoResponse\x12k\n" +
	"\n" +
	"Initialize\x12-.hal.adapters.timetagger.v1.InitializeRequest\x1a..hal.adapters.timetagger.v1.InitializeResponse\x12q\n" +
	"\fDeinitialize\x12/.hal.adapters.timetagger.v1.DeinitializeRequest\x1a0.hal.adapters.timetagger.v1.DeinitializeResponse\x12h\n" +
	"\tGetStatus\x12,.hal.adapters.timetagger.v1.GetStatusRequest\x1a-.hal.adapters.timetagger.v1.GetStatusResponse\x12h\n" +
	"\tSetConfig\x12,.hal.adapters.timetagger.v1.SetConfigRequest\x1a-.hal.adapters.timetagger.v1.SetConfigResponse\x12f\n" +
	"\vAutoRecover\x12*.hal.adapters.common.v1.AutoRecoverRequest\x1a+.hal.adapters.common.v1.AutoRecoverResponse\x12Q\n" +
	"\x04Tune\x12#.hal.adapters.common.v1.TuneRequest\x1a$.hal.adapters.common.v1.TuneResponse\x12\x86\x01\n" +
	"\x13StartDataCollection\x126.hal.adapters.timetagger.v1.StartDataCollectionRequest\x1a7.hal.adapters.timetagger.v1.StartDataCollectionResponse\x12\x83\x01\n" +
	"\x12StopDataCollection\x125.hal.adapters.timetagger.v1.StopDataCollectionRequest\x1a6.hal.adapters.timetagger.v1.StopDataCollectionResponse\x12q\n" +
	"\fTriggerEvent\x12/.hal.adapters.timetagger.v1.TriggerEventRequest\x1a0.hal.adapters.timetagger.v1.TriggerEventResponseB\x91\x02\n" +
	"\x1ecom.hal.adapters.timetagger.v1B\x0fTimetaggerProtoP\x01ZSgithub.com/outshift-open/quantum-hal/sdk/go/hal/adapters/timetagger/v1;timetaggerv1\xa2\x02\x03HAT\xaa\x02\x1aHal.Adapters.Timetagger.V1\xca\x02\x1aHal\\Adapters\\Timetagger\\V1\xe2\x02&Hal\\Adapters\\Timetagger\\V1\\GPBMetadata\xea\x02\x1dHal::Adapters::Timetagger::V1b\x06proto3"

var (
	file_hal_adapters_timetagger_v1_timetagger_proto_rawDescOnce sync.Once
	file_hal_adapters_timetagger_v1_timetagger_proto_rawDescData []byte
)

func file_hal_adapters_timetagger_v1_timetagger_proto_rawDescGZIP() []byte {
	file_hal_adapters_timetagger_v1_timetagger_proto_rawDescOnce.Do(func() {
		file_hal_adapters_timetagger_v1_timetagger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hal_adapters_timetagger_v1_timetagger_proto_rawDesc), len(file_hal_adapters_timetagger_v1_timetagger_proto_rawDesc)))
	})
	return file_hal_adapters_timetagger_v1_timetagger_proto_rawDescData
}

var file_hal_adapters_timetagger_v1_timetagger_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_hal_adapters_timetagger_v1_timetagger_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_hal_adapters_timetagger_v1_timetagger_proto_goTypes = []any{
	(TimeTaggerState)(0),                   // 0: hal.adapters.timetagger.v1.TimeTaggerState
	(*GetProductInfoRequest)(nil),          // 1: hal.adapters.timetagger.v1.GetProductInfoRequest
	(*GetProductInfoResponse)(nil),         // 2: hal.adapters.timetagger.v1.GetProductInfoResponse
	(*InitializeRequest)(nil),              // 3: hal.adapters.timetagger.v1.InitializeRequest
	(*InitializeResponse)(nil),             // 4: hal.adapters.timetagger.v1.InitializeResponse
	(*DeinitializeRequest)(nil),            // 5: hal.adapters.timetagger.v1.DeinitializeRequest
	(*DeinitializeResponse)(nil),           // 6: hal.adapters.timetagger.v1.DeinitializeResponse
	(*GetStatusRequest)(nil),               // 7: hal.adapters.timetagger.v1.GetStatusRequest
	(*GetStatusResponse)(nil),              // 8: hal.adapters.timetagger.v1.GetStatusResponse
	(*SetConfigRequest)(nil),               // 9: hal.adapters.timetagger.v1.SetConfigRequest
	(*SetConfigResponse)(nil),              // 10: hal.adapters.timetagger.v1.SetConfigResponse
	(*StartDataCollectionRequest)(nil),     // 11: hal.adapters.timetagger.v1.StartDataCollectionRequest
	(*StartDataCollectionResponse)(nil),    // 12: hal.adapters.timetagger.v1.StartDataCollectionResponse
	(*StopDataCollectionRequest)(nil),      // 13: hal.adapters.timetagger.v1.StopDataCollectionRequest
	(*StopDataCollectionResponse)(nil),     // 14: hal.adapters.timetagger.v1.StopDataCollectionResponse
	(*TriggerEventRequest)(nil),            // 15: hal.adapters.timetagger.v1.TriggerEventRequest
	(*TriggerEventResponse)(nil),           // 16: hal.adapters.timetagger.v1.TriggerEventResponse
	(*v1.HealthCheckRequest)(nil),          // 17: hal.adapters.common.v1.HealthCheckRequest
	(*v1.ResourceHealthCheckRequest)(nil),  // 18: hal.adapters.common.v1.ResourceHealthCheckRequest
	(*v1.AutoRecoverRequest)(nil),          // 19: hal.adapters.common.v1.AutoRecoverRequest
	(*v1.TuneRequest)(nil),                 // 20: hal.adapters.common.v1.TuneRequest
	(*v1.HealthCheckResponse)(nil),         // 21: hal.adapters.common.v1.HealthCheckResponse
	(*v1.ResourceHealthCheckResponse)(nil), // 22: hal.adapters.common.v1.ResourceHealthCheckResponse
	(*v1.AutoRecoverResponse)(nil),         // 23: hal.adapters.common.v1.AutoRecoverResponse
	(*v1.TuneResponse)(nil),                // 24: hal.adapters.common.v1.TuneResponse
}
var file_hal_adapters_timetagger_v1_timetagger_proto_depIdxs = []int32{
	0,  // 0: hal.adapters.timetagger.v1.GetStatusResponse.state:type_name -> hal.adapters.timetagger.v1.TimeTaggerState
	17, // 1: hal.adapters.timetagger.v1.AdapterTimeTaggerService.HealthCheck:input_type -> hal.adapters.common.v1.HealthCheckRequest
	18, // 2: hal.adapters.timetagger.v1.AdapterTimeTaggerService.ResourceHealthCheck:input_type -> hal.adapters.common.v1.ResourceHealthCheckRequest
	1,  // 3: hal.adapters.timetagger.v1.AdapterTimeTaggerService.GetProductInfo:input_type -> hal.adapters.timetagger.v1.GetProductInfoRequest
	3,  // 4: hal.adapters.timetagger.v1.AdapterTimeTaggerService.Initialize:input_type -> hal.adapters.timetagger.v1.InitializeRequest
	5,  // 5: hal.adapters.timetagger.v1.AdapterTimeTaggerService.Deinitialize:input_type -> hal.adapters.timetagger.v1.DeinitializeRequest
	7,  // 6: hal.adapters.timetagger.v1.AdapterTimeTaggerService.GetStatus:input_type -> hal.adapters.timetagger.v1.GetStatusRequest
	9,  // 7: hal.adapters.timetagger.v1.AdapterTimeTaggerService.SetConfig:input_type -> hal.adapters.timetagger.v1.SetConfigRequest
	19, // 8: hal.adapters.timetagger.v1.AdapterTimeTaggerService.AutoRecover:input_type -> hal.adapters.common.v1.AutoRecoverRequest
	20, // 9: hal.adapters.timetagger.v1.AdapterTimeTaggerService.Tune:input_type -> hal.adapters.common.v1.TuneRequest
	11, // 10: hal.adapters.timetagger.v1.AdapterTimeTaggerService.StartDataCollection:input_type -> hal.adapters.timetagger.v1.StartDataCollectionRequest
	13, // 11: hal.adapters.timetagger.v1.AdapterTimeTaggerService.StopDataCollection:input_type -> hal.adapters.timetagger.v1.StopDataCollectionRequest
	15, // 12: hal.adapters.timetagger.v1.AdapterTimeTaggerService.TriggerEvent:input_type -> hal.adapters.timetagger.v1.TriggerEventRequest
	21, // 13: hal.adapters.timetagger.v1.AdapterTimeTaggerService.HealthCheck:output_type -> hal.adapters.common.v1.HealthCheckResponse
	22, // 14: hal.adapters.timetagger.v1.AdapterTimeTaggerService.ResourceHealthCheck:output_type -> hal.adapters.common.v1.ResourceHealthCheckResponse
	2,  // 15: hal.adapters.timetagger.v1.AdapterTimeTaggerService.GetProductInfo:output_type -> hal.adapters.timetagger.v1.GetProductInfoResponse
	4,  // 16: hal.adapters.timetagger.v1.AdapterTimeTaggerService.Initialize:output_type -> hal.adapters.timetagger.v1.InitializeResponse
	6,  // 17: hal.adapters.timetagger.v1.AdapterTimeTaggerService.Deinitialize:output_type -> hal.adapters.timetagger.v1.DeinitializeResponse
	8,  // 18: hal.adapters.timetagger.v1.AdapterTimeTaggerService.GetStatus:output_type -> hal.adapters.timetagger.v1.GetStatusResponse
	10, // 19: hal.adapters.timetagger.v1.AdapterTimeTaggerService.SetConfig:output_type -> hal.adapters.timetagger.v1.SetConfigResponse
	23, // 20: hal.adapters.timetagger.v1.AdapterTimeTaggerService.AutoRecover:output_type -> hal.adapters.common.v1.AutoRecoverResponse
	24, // 21: hal.adapters.timetagger.v1.AdapterTimeTaggerService.Tune:output_type -> hal.adapters.common.v1.TuneResponse
	12, // 22: hal.adapters.timetagger.v1.AdapterTimeTaggerService.StartDataCollection:output_type -> hal.adapters.timetagger.v1.StartDataCollectionResponse
	14, // 23: hal.adapters.timetagger.v1.AdapterTimeTaggerService.StopDataCollection:output_type -> hal.adapters.timetagger.v1.StopDataCollectionResponse
	16, // 24: hal.adapters.timetagger.v1.AdapterTimeTaggerService.TriggerEvent:output_type -> hal.adapters.timetagger.v1.TriggerEventResponse
	13, // [13:25] is the sub-list for method output_type
	1,  // [1:13] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_hal_adapters_timetagger_v1_timetagger_proto_init() }
func file_hal_adapters_timetagger_v1_timetagger_proto_init() {
	if File_hal_adapters_timetagger_v1_timetagger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hal_adapters_timetagger_v1_timetagger_proto_rawDesc), len(file_hal_adapters_timetagger_v1_timetagger_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hal_adapters_timetagger_v1_timetagger_proto_goTypes,
		DependencyIndexes: file_hal_adapters_timetagger_v1_timetagger_proto_depIdxs,
		EnumInfos:         file_hal_adapters_timetagger_v1_timetagger_proto_enumTypes,
		MessageInfos:      file_hal_adapters_timetagger_v1_timetagger_proto_msgTypes,
	}.Build()
	File_hal_adapters_timetagger_v1_timetagger_proto = out.File
	file_hal_adapters_timetagger_v1_timetagger_proto_goTypes = nil
	file_hal_adapters_timetagger_v1_timetagger_proto_depIdxs = nil
}
